logger: "console"
log: "error"
warnings: 0
debug: 0
show_errors: 1
route_cache: 1
auto_reload: 0
port: 9055
drs_url: http://ecenter.fnal.gov:8055
gearman:
   servers: 
       xenmon.fnal.gov: ['10121']
