<?php

include_once('ecenter_dashboard.features.inc');

/**
 * Implementation of hook_menu().
 */
function ecenter_dashboard_menu() {
  $items['ecenter-dashboard'] = array(
    'page callback' => 'theme',
    'page arguments' => array('ecenter_dashboard'),
    'title' => 'Dashboard',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function ecenter_dashboard_theme() {
  return array(
    'ecenter_dashboard' => array(
      'template' => 'ecenter-dashboard',
      'arguments' => array(),
    ),
  );
}

/**
 * E-Center dashboard callback
 */
function template_preprocess_ecenter_dashboard(&$vars) {
  global $user;

  drupal_add_js(libraries_get_path('raphael') .'/raphael-min.js');
  drupal_add_js(libraries_get_path('qtip') .'/jquery.qtip.js');
  drupal_add_js(drupal_get_path('module', 'ecenter_dashboard') .'/js/ecenter-dashboard.js');

  if ($user->uid) {
    module_load_include('inc', 'date_api', 'date_api_elements');
    $now = time() - 1800;
    $offset = 3600 * 3;
    $inc = 60;
    $tz = timezone_open('UTC');
    $end = date_make_date($now, $tz, DATE_UNIX);
    $start = date_make_date($now - $offset, $tz, DATE_UNIX);
    date_increment_round($start, $inc);
    date_increment_round($end, $inc);
    $start = date_format($start, 'Y-m-d H:i:00');
    $end = date_format($end, 'Y-m-d H:i:00');

    $hub = (!empty($user->ecenter_default_hub)) ? $user->ecenter_default_hub : variable_get('ecenter_site_default_hub', 'FNAL');
    $data = ecenter_network_get_site_centric_data($hub, $start, $end);
    drupal_add_js(array('ecenterNetwork' => array('siteData' => $data)), 'setting');

    $vars['main_content'] = array(
      'site_view' => array(
        'content' => '<div id="site-view-description"><h2>'. t('@site status', array('@site' => $hub)) .'</h2>' . 
          '<p>'. t('<span class="start">@start</span> <span class="separator">to</span> <span class="end">@end</span>', array('@start' => $start, '@end' => $end)) .'</p></div><div id="site-view-svg"></div>',
      ),
      'activity' => array(
        'subject' => t('Site activity'),
        'description' => t('Activity on the site and in your groups'),
        'content' => views_embed_view('ecenter_dashboard_activity', 'block_personal'),
      ),
    );
    $vars['secondary_content'] = array(
      'tools' => array(
        'subject' => t('Tools'),
        'content' => theme('links', menu_navigation_links('menu-action-links')),
      ),
      'hot-comments' => array(
        'subject' => t('Hot conversations'),
        'description' => t('The most active public conversations in the past 2 weeks'),
        'content' => views_embed_view('ecenter_dashboard_hot_comments', 'block'),
      ),
      'hot-content' => array(
        'subject' => t('Most popular content'),
        'description' => t('The most popular content in the past month'),
        'content' => views_embed_view('ecenter_dashboard_hot_content', 'block'),
      ),
    );
  }
  else {
    drupal_set_title('');
    $vars['main_content'] = array(
      'carousel' => array(
        'subject' => t('What is E-Center?'),
        'content' => views_embed_view('ecenter_dashboard_carousel', 'block'),
      ),
      'activity' => array(
        'subject' => t('Site activity'),
        'description' => t('All public activity'),
        'content' => views_embed_view('ecenter_dashboard_activity', 'block_public'),
      ),
    );
    $vars['secondary_content'] = array(
      'login' => module_invoke('ecenter_core', 'block', 'view', 'dashboard_login'),
      'hot-comments' => array(
        'subject' => t('Hot conversations'),
        'description' => t('The most active public conversations in the past 2 weeks'),
        'content' => views_embed_view('ecenter_dashboard_hot_comments', 'block'),
      ),
      'hot-content' => array(
        'subject' => t('Most popular content'),
        'description' => t('The most popular content in the past month'),
        'content' => views_embed_view('ecenter_dashboard_hot_content', 'block'),
      ),
    );
  }
}

function ecenter_dashboard_cron() {
  module_load_include('inc', 'date_api', 'date_api_elements');
  $now = time();
  $offset = 3600 * 3;
  $inc = 60;
  $tz = timezone_open('UTC');
  $end = date_make_date($now, $tz, DATE_UNIX);
  $start = date_make_date($now - $offset, $tz, DATE_UNIX);
  date_increment_round($start, $inc);
  date_increment_round($end, $inc);
  $start = date_format($start, 'Y-m-d H:i:00');
  $end = date_format($end, 'Y-m-d H:i:00');

  $hubs = ecenter_network_get_hops();
  foreach ($hubs['hubs'] as $key => $hop) {
    if ($key != 'PPPL' && $key != 'SNLL' && $key != 'LLNL') {
      $data = ecenter_network_get_site_centric_data($key, $start, $end);
    }
  }
}
