<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function ecenter_dashboard_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'type' => 'snippet',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1323980637',
  'changed' => '1323980637',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '1',
  'title' => 'An API for network data',
  'body' => '<div style="font-family: Lato; position: relative; width: 555px;">
  <div style="position: absolute;">
    <img src="https://ecenter.fnal.gov/sites/default/files/snippet/image/ecenter-architecture-detail_0.png" height="309" width="555" />
  </div>
  
  <div style="position: absolute; left: 20px; top: 50px;">
    <h3 style="font-size: 29px; border: none; margin-bottom: 15px;">
      A modern web services API for retrieving network data
    </h3>
    
    <p style="font-size: 19px; color: #000;">
      E-Center\'s <a href="internal:node/73">Data Retrieval Service</a> collects distributed network data in a highly scalable, JSON-powered data source. The data can be used for anomaly detection, forecasting, and historical anlaysis.
    </p>
  </div>
</div>',
  'teaser' => '<div style="font-family: Lato; position: relative; width: 555px;">
  <div style="position: absolute;">
    <img src="https://ecenter.fnal.gov/sites/default/files/snippet/image/ecenter-architecture-detail_0.png" height="309" width="555" />
  </div>
  
  <div style="position: absolute; left: 20px; top: 50px;">
    <h3 style="font-size: 29px; border: none; margin-bottom: 15px;">
      A modern web services API for retrieving network data
    </h3>
    
    <p style="font-size: 19px; color: #000;">
      E-Center\'s <a href="internal:node/73">Data Retrieval Service</a> collects distribut',
  'log' => '',
  'revision_timestamp' => '1323980637',
  'format' => '4',
  'name' => 'admin',
  'picture' => '',
  'data' => 'a:0:{}',
  'path' => 'content/api-network-data',
  'field_snippet_image' => array(),
  'og_groups_both' => array(),
  'og_groups' => array(),
  'tableofcontents_toc_automatic' => '0',
  'last_comment_timestamp' => '1323980637',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '12245122-275b-11e1-b676-0026b9b97a6a',
  'revision_uuid' => '12248dcc-275b-11e1-b676-0026b9b97a6a',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-12-15 14:23:57 -0600',
);
  $nodes[] = array(
  'type' => 'snippet',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1323980681',
  'changed' => '1323980681',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '1',
  'title' => 'Visualize network performance',
  'body' => '<div style="float: left; width: 555px;">
  <div style="float: left; width: 350px; margin-right: 20px;">
    <img src="https://ecenter.fnal.gov/sites/default/files/snippet/image/ecenter-screenshot-weathermap.jpg" height="309" width="350" />
  </div>
  
  <h3 style="font-family: Lato; font-size: 21px; border: none; margin-bottom: 15px;">
    Advanced network diagnostics
  </h3>
  
  <p style="font-size: 15px;">
    Explore and discuss end-to-end network data with the <a href="/network">weathermap</a>.
  </p>
  
  <p style="font-size: 15px;">
    Check the status of the <a href="/network/health">measurement mesh</a>.
  </p>
  
  <p style="font-size: 15px;">
    See network data relevant to your site when you <a href="/user/register">register</a>.
  </p>
</div>',
  'teaser' => '<div style="float: left; width: 555px;">
  <div style="float: left; width: 350px; margin-right: 20px;">
    <img src="https://ecenter.fnal.gov/sites/default/files/snippet/image/ecenter-screenshot-weathermap.jpg" height="309" width="350" />
  </div>
  
  <h3 style="font-family: Lato; font-size: 21px; border: none; margin-bottom: 15px;">
    Advanced network diagnostics
  </h3>
  
  <p style="font-size: 15px;">
    Explore and discuss end-to-end network data with the <a href="/network">weathermap</a>.
  </p>',
  'log' => '',
  'revision_timestamp' => '1323980681',
  'format' => '4',
  'name' => 'admin',
  'picture' => '',
  'data' => 'a:0:{}',
  'path' => 'content/visualize-network-performance',
  'field_snippet_image' => array(),
  'og_groups_both' => array(),
  'og_groups' => array(),
  'tableofcontents_toc_automatic' => '0',
  'last_comment_timestamp' => '1323980681',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '12246388-275b-11e1-b676-0026b9b97a6a',
  'revision_uuid' => '12249ede-275b-11e1-b676-0026b9b97a6a',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-12-15 14:24:41 -0600',
);
  $nodes[] = array(
  'type' => 'snippet',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1323980716',
  'changed' => '1323980716',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  'revision_uid' => '1',
  'title' => 'Knowledge sharing & collaboration',
  'body' => '<div style="float: left; width: 540px; margin-left: 15px;">
  <div style="float: right; width: 300px; margin-left: 20px;">
    <img src="https://ecenter.fnal.gov/sites/default/files/snippet/image/ecenter-screenshot-wiki.jpg" height="289" width="300" />
  </div>
  
  <h3 style="font-size: 18px; border: none; margin-bottom: 15px;">
    Group-based knowledge sharing and collaboration
  </h3>
  
  <p style="font-size: 14px;">
    <a href="/issues">Share and discuss</a> network data and network-related issues.
  </p>
  
  <p style="font-size: 14px;">
    Search, create, and edit <a href="/wiki">articles in our wiki</a>
  </p>
  
  <p style="font-size: 14px;">
    <a href="/og">Join a group</a> to follow conversations relevant to you or create a working group.
  </p>
</div>',
  'teaser' => '<div style="float: left; width: 540px; margin-left: 15px;">
  <div style="float: right; width: 300px; margin-left: 20px;">
    <img src="https://ecenter.fnal.gov/sites/default/files/snippet/image/ecenter-screenshot-wiki.jpg" height="289" width="300" />
  </div>
  
  <h3 style="font-size: 18px; border: none; margin-bottom: 15px;">
    Group-based knowledge sharing and collaboration
  </h3>
  
  <p style="font-size: 14px;">
    <a href="/issues">Share and discuss</a> network data and network-related issues.
  </p>',
  'log' => '',
  'revision_timestamp' => '1323980716',
  'format' => '4',
  'name' => 'admin',
  'picture' => '',
  'data' => 'a:0:{}',
  'path' => 'content/knowledge-sharing-collaboration',
  'field_snippet_image' => array(),
  'og_groups_both' => array(),
  'og_groups' => array(),
  'tableofcontents_toc_automatic' => '0',
  'last_comment_timestamp' => '1323980716',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'uuid' => '12246fea-275b-11e1-b676-0026b9b97a6a',
  'revision_uuid' => '1224ab90-275b-11e1-b676-0026b9b97a6a',
  'pathauto_perform_alias' => FALSE,
  'date' => '2011-12-15 14:25:16 -0600',
);
  return $nodes;
}
