<?php

include_once('ecenter_dashboard.features.inc');

/**
 * Implementation of hook_menu().
 */
function ecenter_dashboard_menu() {
  $items['ecenter-dashboard'] = array(
    'page callback' => 'theme',
    'page arguments' => array('ecenter_dashboard'),
    'title' => 'Dashboard',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function ecenter_dashboard_theme() {
  return array(
    'ecenter_dashboard' => array(
      'template' => 'ecenter-dashboard',
      'arguments' => array(),
    ),
  );
}

/**
 * E-Center dashboard callback
 */
function template_preprocess_ecenter_dashboard(&$vars) {
  global $user;

  drupal_add_js(libraries_get_path('raphael') .'/raphael-min.js');
  drupal_add_js(libraries_get_path('qtip') .'/jquery.qtip.js');
  drupal_add_js(drupal_get_path('module', 'ecenter_dashboard') .'/js/ecenter-dashboard.js');

  if ($user->uid) {
    $src = (!empty($user->ecenter_default_hub)) ? $user->ecenter_default_hub : variable_get('ecenter_site_default_hub', 'FNAL');
    $raw_data = ecenter_network_get_recent_scv_results('hub:'. $src, 3600);

    $site_data = array('source' => $raw_data['data']['source'], 'destinations' => array());
    foreach ($raw_data['data']['destinations'] as $hub => $data) {
      $site_data['destinations'][] = array(
        'hub' => $hub,
        'data' => $data,
        'markup' => theme('ecenter_network_site_centric_data', $data),
      );
    }
    drupal_add_js(array('ecenterNetwork' => array('siteData' => $site_data)), 'setting');

    $vars['main_content'] = array(
      'site_view' => array(
        'content' => 
          '<div id="site-view-description"><h2>'. t('@site status', array('@site' => $src)) .'</h2>' . 
          '<p>'. t('<span class="start">@start</span> <span class="separator">to</span> <span class="end">@end</span>',
            array('@start' => $raw_data['start'], '@end' => $raw_data['end'])) .'</p>' .
          '<p>'. l('View more sites &raquo;', 'network/sites', array('html' => TRUE)) .'</p></div>' . 
          '<div id="site-view-svg"></div>',
      ),
      'activity' => array(
        'subject' => t('Site activity'),
        'description' => t('Activity on the site and in your groups'),
        'content' => views_embed_view('ecenter_dashboard_activity', 'block_personal'),
      ),
    );
    $vars['secondary_content'] = array(
      'tools' => array(
        'subject' => t('Tools'),
        'content' => theme('links', menu_navigation_links('menu-action-links')),
      ),
      'hot-comments' => array(
        'subject' => t('Hot conversations'),
        'description' => t('The most active public conversations in the past 2 weeks'),
        'content' => views_embed_view('ecenter_dashboard_hot_comments', 'block'),
      ),
      'hot-content' => array(
        'subject' => t('Most popular content'),
        'description' => t('The most popular content in the past month'),
        'content' => views_embed_view('ecenter_dashboard_hot_content', 'block'),
      ),
    );
  }
  else {
    drupal_set_title('');
    $vars['main_content'] = array(
      'carousel' => array(
        'subject' => t('What is E-Center?'),
        'content' => views_embed_view('ecenter_dashboard_carousel', 'block'),
      ),
      'activity' => array(
        'subject' => t('Site activity'),
        'description' => t('All public activity'),
        'content' => views_embed_view('ecenter_dashboard_activity', 'block_public'),
      ),
    );
    $vars['secondary_content'] = array(
      'login' => module_invoke('ecenter_core', 'block', 'view', 'dashboard_login'),
      'hot-comments' => array(
        'subject' => t('Hot conversations'),
        'description' => t('The most active public conversations in the past 2 weeks'),
        'content' => views_embed_view('ecenter_dashboard_hot_comments', 'block'),
      ),
      'hot-content' => array(
        'subject' => t('Most popular content'),
        'description' => t('The most popular content in the past month'),
        'content' => views_embed_view('ecenter_dashboard_hot_content', 'block'),
      ),
    );
  }
}

/**
 * Implementation of hook_content_build_modes().
 */
function ecenter_dashboard_content_build_modes() {
  return array(
    'ecenter' => array(
      'title' => t('E-Center'),
      'build modes' => array(
        'ecenter_activity' => array(
          'title' => 'E-Center activity',
          'views style' => TRUE,
        ),
      ),
    ),
  );
}

/**
 * Implementation of hook_uuid_node_features_rebuild_alter().
 */
function ecenter_dashboard_uuid_node_features_rebuild_alter(&$node, $module) {
  if ($node->type == 'snippet' && $module == 'ecenter_dashboard') {
    $flag = flag_get_flag('ecenter_dashboard_carousel');
    $flag->flag('flag', $node->nid);
  }
}

