<?php
// $Id$

/**
 * @file date_widgets.module
 */

function date_widgets_theme() {
  return array(
    'date_range_popout' => array('arguments' => array('element' => NULL)),
  );
}


function date_widgets_elements() {
  return array(
    'date_range_popout' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#date_timezone' => date_default_timezone_name(),
      '#date_format' => variable_get('date_format_short', 'Y-m-d H:i'),
      '#time_increment' => 1,
      '#date_year_range' => '-3:+3',
      '#process' => array('date_widgets_range_popout_process'),
      //'#columns' => array('value', 'value2', 'timezone', 'offset', 'offset2'),
    ),
  );
}

function date_widgets_range_popout_process($element, $edit, &$form_state, $form) {
  //dpm('hi');
  return $element;
}

function theme_date_range_popout($element) {
  $output = '';
  if (isset($element['#children'])) {
    $output = $element['#children'];
  }
  $element['#type'] = 'textfield';
  return '<div class="date-range-popout">'. theme('form_element', $element, $output) .'</div>'; 
}
