<?php
// $Id$

/**
 * @file
 * E-Center network query interface.
 */

function ecenter_weathermap_menu() {
  $items['weathermap'] = array(
    'title' => 'E-Center Weather Map',
    'page callback' => 'ecenter_weathermap',
    //'page arguments' => array(),
    'access arguments' => array('access ecenter weathermap'),
    'type' => MENU_CALLBACK,
  );
  $items['weathermap/data/%/hub-select']  = array(
    'title' => 'E-Center Weather Map',
    'page callback' => 'ecenter_weathermap_ajax',
    'page arguments' => array(2, 3),
    'access arguments' => array('access ecenter weathermap'),
    'file' => 'includes/ecenter_weathermap.ajax.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/ecenter'] = array(
    'title' => 'E-Center Network Query Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ecenter_weathermap_admin_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer ecenter weathermap'),
    'description' => 'Configure the E-Center weather map.',
    'file' => 'includes/ecenter_weathermap.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/*function ecenter_weathermap_services() {
  $client = ecenter_weathermap_get_client();
  $services = $client->getDestinationServices($_POST['src_ip']);
  drupal_set_header('HTTP/1.1 '. $services['code']);

  if ($services['code'] == 200) {
    foreach ($services['response']->services as $service) {
      $options[$service->ip_addr] = theme('ecenter_weathermap_service_option', $service);
    }

    $form = ecenter_weathermap_select_form(array(), array());
    $element = $form['dst_ip'];
    $element['#options'] = $options;
    $element['#name'] = 'dst_ip';
    $element['#id'] = 'edit-dst-ip';
    $element['#parents'] = array();
    echo theme('quickselect', $element);
  }
  exit;
}*/

function ecenter_weathermap_perm() {
  return array('access ecenter weathermap', 'administer ecenter weathermap');
}

function ecenter_weathermap_select_form($form_state, $services, $src_ip = False, $dst_ip = False, $start = False, $end = False) {
  $quickselect_options = array(
    'emulateDropdown' => TRUE,
    'maxHeight' => '400px',
    'exactMatch' => TRUE,
  );

  $form = array(
    'src_ip' => array(
      '#title'               => t('Source IP'),
      '#type'                => 'quickselect',
      '#options'             => $services,
      '#cols'                => 50,
      '#quickselect_options' => $quickselect_options,
      '#required'            => TRUE,
    ),
    'dst_ip' => array(
      '#title'               => t('Destination IP'),
      '#type'                => 'quickselect',
      '#options'             => $services,
      '#cols'                => 50,
      '#required'            => TRUE,
      '#quickselect_options' => $quickselect_options,
    ),
    'submit' => array(
      '#value' => t('Submit'),
      '#type' => 'submit',
    ),
  );

  return $form;
}

function ecenter_weathermap_select_form_submit($form, &$form_state) {
  $form_state['redirect'] = array('weathermap', 'ajax=1&src_ip='. $form_state['values']['src_ip'] .'&dst_ip='. $form_state['values']['dst_ip']);
}

function ecenter_weathermap() {
  // We need quickselect to get added to behaviors first, so it executes first
  drupal_add_js(drupal_get_path('module', 'quickselect') .'/js/quickselect-behavior.js');
  drupal_add_js(drupal_get_path('module', 'ecenter_weathermap') .'/js/query.js');

  drupal_add_css(drupal_get_path('module', 'ecenter_weathermap') .'/css/plot.css');

  // Get services
  $client = ecenter_weathermap_get_client();
  $hops = $client->getHubs();
  $options = array('' => 'Select a node');
  foreach ($hops['response'] as $hop) {
    $options[$hop->ip_noted] = theme('ecenter_weathermap_hop_option', $hop);
  }
  $form = drupal_get_form('ecenter_weathermap_select_form', $options);

  /*list($src_ip, $dst_ip) = array($_REQUEST['src_ip'], $_REQUEST['dst_ip']);
  if ($src_ip && $dst_ip) {
    $data = $client->getPathData($src_ip, $dst_ip, '2009-06-01 12:00:00', '2010-07-01 12:00:00');
    dpm($data);
  }

  if ($_REQUEST['ajax']) {
    // ...
  }*/

  return $form;
}

function ecenter_weathermap_get_client() {
  static $client = False;
  if (!$client) {
    require_once(dirname(__FILE__) . '/client.php');
    $host = variable_get('ecenter_weathermap_host', 'localhost');
    $port = variable_get('ecenter_weathermap_port', 8000);
    $dir = variable_get('ecenter_weathermap_basedir', '');
    $client = new Ecenter_Data_Service_Client($host, $port, $dir);
  }
  return $client;
}

/**
 * ecenter_weathermap_sanitize_get
 * Sanitize the get array
 */
function ecenter_weathermap_sanitize_get() {
  if (!function_exists('filter_input')) {
    return $_GET;
  }
  $get = array();
  foreach (array_keys($_GET) as $key) {
    $get[$key] = filter_input(INPUT_GET, $key, FILTER_SANITIZE_STRING);
  }
  return $get;
}

function ecenter_weathermap_theme() {
  //$options = array('file' => drupal_get_path('module', 'ecenter_weathermap') .'/includes/ecenter_weathermap.theme.inc');
  $path = array(
    'path' => drupal_get_path('module', 'ecenter_weathermap') .'/includes',
    'file' => 'ecenter_weathermap.theme.inc'
  );
  return array(
    'ecenter_weathermap_hop_option' => 
      array('arguments' => array('hop' => NULL)) + $path,
  );
}
