<?php
// $Id$

/**
 * @file
 * E-Center network query interface.
 */

function ecenter_network_query_menu() {
  $items['weathermap'] = array(
    'title' => 'E-Center Weather Map',
    'page callback' => 'ecenter_network_query',
    //'page arguments' => array(),
    'access arguments' => array('access ecenter weathermap'),
    'type' => MENU_CALLBACK,
  );
  $items['weathermap/js/services']  = array(
    'title' => 'E-Center Weather Map',
    'page callback' => 'ecenter_network_query_services',
    //'page arguments' => array(3),
    'access arguments' => array('access ecenter weathermap'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function ecenter_network_query_services() {
  $client = ecenter_network_query_get_client();
  $services = $client->getDestinationServices($_POST['src_ip']);
  drupal_set_header('HTTP/1.1 '. $services['code']);

  if ($services['code'] == 200) {
    foreach ($services['response']->services as $service) {
      $options[$service->ip_addr] = theme('ecenter_network_query_service_option', $service);
    }

    $form = ecenter_network_query_select_form(array(), array());
    $element = $form['dst_ip'];
    $element['#options'] = $options;
    $element['#name'] = 'dst_ip';
    $element['#id'] = 'edit-dst-ip';
    $element['#parents'] = array();
    echo theme('quickselect', $element);
  }
  exit;
}

function ecenter_network_query_perm() {
  return array('access ecenter weathermap');
}

function ecenter_network_query_select_form($form_state, $services, $src_ip = False, $dst_ip = False, $start = False, $end = False) {
  $quickselect_options = array(
    'emulateDropdown' => TRUE,
    'maxHeight' => '400px',
    'exactMatch' => TRUE,
  );

  $form = array(
    'src_ip' => array(
      '#title'               => t('Source IP'),
      '#type'                => 'quickselect',
      '#options'             => $services,
      '#cols'                => 50,
      '#quickselect_options' => $quickselect_options,
      '#required'            => TRUE,
    ),
    'dst_ip' => array(
      '#title'               => t('Destination IP'),
      '#type'                => 'quickselect',
      '#options'             => $services,
      '#cols'                => 50,
      '#required'            => TRUE,
      '#quickselect_options' => $quickselect_options,
    ),
    'submit' => array(
      '#value' => t('Submit'),
      '#type' => 'submit',
    ),
  );

  return $form;
}

function ecenter_network_query_select_form_submit($form, &$form_state) {
  $form_state['redirect'] = array('weathermap', 'ajax=1&src_ip='. $form_state['values']['src_ip'] .'&dst_ip='. $form_state['values']['dst_ip']);
}

function ecenter_network_query() {
  // We need quickselect to get added to behaviors first, so it executes first
  drupal_add_js(drupal_get_path('module', 'quickselect') .'/js/quickselect-behavior.js');
  drupal_add_js(drupal_get_path('module', 'ecenter_network_query') .'/js/query.js');

  // Get services
  $client = ecenter_network_query_get_client();
  $services = $client->getServices();

  $options = array('' => 'Select a node');
  foreach ($services['response']->services as $service) {
    $options[$service->ip_addr] = theme('ecenter_network_query_service_option', $service);
  }

  $form = drupal_get_form('ecenter_network_query_select_form', $options);

  list($src_ip, $dst_ip) = array($_REQUEST['src_ip'], $_REQUEST['dst_ip']);
  if ($src_ip && $dst_ip) {
    $data = $client->getPathData($src_ip, $dst_ip, '2009-06-01 12:00:00', '2010-07-01 12:00:00');
    dpm($data);
  }

  if ($_REQUEST['ajax']) {
    // ...
  }

  return $form;
}

function ecenter_network_query_get_client() {
  static $client = False;
  if (!$client) {
    require_once(dirname(__FILE__) . '/client.php');
    $host = variable_get('ecenter_network_query_host', 'localhost');
    $port = variable_get('ecenter_network_query_port', 8000);
    $dir = variable_get('ecenter_network_query_directory', 'ecenter');
    $client = new Ecenter_Data_Service_Client($host, $port, $dir);
  }
  return $client;
}

function ecenter_network_query_theme() {
  return array(
    'ecenter_network_query_service_option' => array('arguments' => array('service' => NULL))
  );
}

/**
 * Theme services for use in options list.  Should always return plaintext!
 */
function theme_ecenter_network_query_service_option($service) {
  return $service->name .' ('. $service->ip_addr .')';
}
