<?php
// $Id$

/**
 * @file
 * Provides functional tests for the E-center project and a sandbox for 
 */

function ecenter_test_menu() {
  $items['admin/ecenter/tests/select-ui'] = array(
    'title' => 'Test form behaviors',
    'page callback' => 'ecenter_test_select_ui',
    'access arguments' => array('access ecenter test pages'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/ecenter/tests/jqplot'] = array(
    'title' => 'E-Center: Test jqPlot charting library',
    'page callback' => 'ecenter_test_jqplot',
    'access arguments' => array('access ecenter test pages'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/ecenter/tests/element'] = array(
    'title' => 'HTML Element Test',
    'page callback' => 'theme',
    'page arguments' => array('ecenter_html_test'),
    'access arguments' => array('access ecenter test pages'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/ecenter/tests/traceroute-render'] = array(
    'title' => 'Test traceroute rendering',
    'page callback' => 'ecenter_test_traceroute_render',
    'access arguments' => array('access ecenter test pages'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function ecenter_test_theme() {
  $path = drupal_get_path('module', 'ecenter_test') .'/tpl';
  return array(
    'ecenter_html_test' => array('arguments' => array(), 'template' => 'ecenter-html-test', 'path' => $path),
    'ecenter_jqplot_test' => array('arguments' => array(), 'template' => 'ecenter-jqplot-test', 'path' => $path),
    'ecenter_traceroute_test' => array('arguments' => array('data' => NULL), 'template' => 'ecenter-traceroute', 'path' => $path),
  );
}

function ecenter_test_forms($form_id, $args) {
  return array(
    'ecenter_test_select_form1' => array('callback' => 'ecenter_test_select_form'),
    'ecenter_test_select_form2' => array(
      'callback' => 'ecenter_test_select_form',
      'callback arguments' => array(array(
        'emulateDropdown' => TRUE,
        'maxHeight' => '400px',
        'exactMatch' => TRUE,
      )),
    ),
  );
}

function ecenter_test_perm() {
  return array('access ecenter test pages');
}

function ecenter_test_select_ui() {
  return drupal_get_form('ecenter_test_select_form1') . drupal_get_form('ecenter_test_select_form2');
}

function ecenter_test_select_form($form_state, $quickselect_options = NULL) {

  $options = _ecenter_test_fake_services();

  // Try to guess proper selection, VERY simple minded currently
  /*$remote_ip = explode('.', $_SERVER['REMOTE_ADDR']);
  foreach ($options as $ip => $option) {
    $row_ip = explode('.', $ip);
    if ($row_ip[0] == $remote_ip[0] && $row_ip[1] == $remote_ip[1]) {
      $default = $ip;
      break;
    }
  }*/

  $form = array(
    'quickselect' => array(
      '#title'         => t('Test select UI and address detection'),
      '#type'          => 'quickselect',
      '#options'       => $options,
      '#cols'          => 50,
      //'#default_value' => $default,
      '#quickselect_options' => $quickselect_options,
    )
  );
  return $form;
}

function ecenter_test_jqplot() {
  $tables = array();
  $results = array();

  // Get some data!
  db_set_active('data');
  foreach (array(5527, 5535, 5565, 5566) as $metaid) {
    $results[] = db_query("SELECT s.timestamp as timestamp, s.utilization as utilization FROM {snmp_data} s WHERE metaid=$metaid ORDER BY s.timestamp LIMIT 100");
  }
  db_set_active('default');

  foreach ($results as $result) {

    $table = array();
    $i = 0;
    while ($row = db_fetch_array($result)) {
      $data = array();
      foreach ($row as $key=>$value) {
        $new_data = array('data' => $value, 'class' => $key);
        if ($key == 'timestamp') {
          $new_data['header'] = TRUE;
          $new_data['data'] = $value * 1000;
        }
        if ($key == 'utilization') {
          $new_data['data'] = $value / 1e+8;
        }
        $data[] = $new_data;
      }
      $table[] = $data;
    }

    $tables[] = theme('ecenter_weathermap_table', array('Timestamp', 'Utilization'), $table, array('class' => 'graph-table'));

  }

  $plot_options = array(
    'width' => 700,
    'height' => 300,
    //'hideTables' => TRUE,
    'plotOptions' => array(
      'seriesDefaults' => array(
        'lineWidth' => 1.5,
        'shadow' => FALSE,
        //'fillAndStroke' => TRUE,
        'fill' => FALSE,
        'color' => '#aaaaaa',
        'threshold' => 1,
        'markerOptions' => array(
          'show' => FALSE,
          'size' => 5,
        ),
      ),
      'axes' => array(
        'xaxis' => array(
          'pad' => 0,
          'autoscale' => TRUE,
          'numberTicks' => 10,
          'renderer' => '$.jqplot.DateAxisRenderer',
          'tickOptions' => array(
            'formatString' => "%H:%M",
          ),
          'label' => t('Time (@date)', array('@date' => $date_label)),
          'labelRenderer' => '$.jqplot.CanvasAxisLabelRenderer',
        ),
        'yaxis' => array(
          'min' => 0,
          'max' => 100,
          'numberTicks' => 6,
          'label' => t('Percent utilization'),
          'labelRenderer' => '$.jqplot.CanvasAxisLabelRenderer',
          'tickOptions' => array(
            'formatString' => '%01.0f%'
          ),
        ),
      ),
      'grid' => array(
        'shadow' => FALSE,
        'borderWidth' => 0,
        'background' => '#dddddd',
        'gridLineColor' => '#ffffff',
      ),
      'highlighter' => array(
        'show' => TRUE,
        'sizeAdjust' => 2,
        'lineWidthAdjust' => 3,
        'tooltipLocation' => 'n',
        'tooltipOffset' => 20,
        'tooltipSeparator' => ': ',
      ),
      'linehighlighter' => array(
        'threshold' => 4,
        'lineScale' => 2,
        'colors' => array(),
      ),
      'cursor' => array(
        'show' => TRUE,
        'showTooltip' => FALSE,
        'zoom' => TRUE,
        'clickReset' => TRUE,
        //'constrainZoomTo' => 'x',
      ),
    ),
  );

  jqplot_register_tablechart('#graph-table', $plot_options);
  return '<div id="graph-table">' . implode('', $tables) . '</div>';
}

function ecenter_test_traceroute_render() {
  drupal_add_js(drupal_get_path('module', 'ecenter_weathermap') .'/js/jquery.traceroute.js');
  drupal_add_js(drupal_get_path('module', 'ecenter_weathermap') .'/js/jquery.datehide.js');
  drupal_add_js(drupal_get_path('module', 'ecenter_weathermap') .'/js/behaviors.js');

  //$client = ecenter_weathermap_get_client('message');
  //result = $client->getData('198.49.208.3', '131.243.24.11', '2010-07-09 14:00:00', '2010-07-09 15:00:00');
  //$data = ecenter_weathermap_parse_response($result, '198.49.208.3', '131.243.24.11');
  //$result = $client->getData('192.12.15.26', '131.243.24.11', '2010-08-11 10:00:00', '2010-08-11 11:00:00');
  //$data = ecenter_weathermap_parse_response($result, '192.12.15.26', '131.243.24.11');
  //$result = $client->getData('131.243.24.11', '198.49.208.3', '2010-08-11 10:00:00', '2010-08-11 11:00:00');
  //$data = ecenter_weathermap_parse_response($result, '131.243.24.11', '198.49.208.3');

  drupal_add_js(array('tracerouteData' => $data['diff']), 'setting');
  drupal_add_js(array('tracerouteMaxLength' => $data['traceroute_max']), 'setting');

  return theme('ecenter_traceroute_test');
}

/*function ecenter_test_jqplot_plugins() {
  $path = drupal_get_path('module', 'ecenter_test');
  return array(
    'linehighlighter' => $path .'/js/jqplot.linehighlighter.js',
  );
}*/

function template_preprocess_ecenter_jqplot_test(&$vars) {}
function template_preprocess_ecenter_html_test(&$vars) {}
function template_preprocess_ecenter_traceroute_test(&$vars) {}
