<?php
// $Id$

/**
 * @file
 * Provides hacks to Drupal content editing to match the E-center workflow.
 */

/**
 * Implementation hook_form_alter().
 */
function ecenter_editing_form_alter(&$form, &$form_state, $form_id) {
  // Override image insertion form when making AHAH callback
  // @TODO:  Why doesn't the form-specific version work?
  if ($form_id == 'content_add_more_js') {
    _ecenter_editing_process_field_image($form['field_image']);
  }

  // Node forms
  if ($form['#id'] != 'node-form') {
    return;
  }

  $node = $form['#node'];

  // Universal overrides

  // Override revision log to be more wiki-like
  unset($form['revision_information']['#title']);
  
  $form['revision_information']['#type'] = 'markup';
  $form['revision_information']['#collapsible'] = FALSE;
  $form['revision_information']['log']['#title'] = t('Revision message');
  $form['revision_information']['log']['#rows'] = 5;
  $form['revision_information']['log']['#cols'] = 50;
  $form['revision_information']['log']['#description'] = t(
    'Provide a short description of the changes made to this @type.',
    array('@type' => drupal_strtolower(node_get_types('name', $node)))
  );

  // Remove options for internal Drupal workflow states
  $form['options']['promote']['#access'] = FALSE;
  $form['options']['sticky']['#access'] = FALSE;

  // Remove summary / teaser silliness
  $form['body_field']['teaser_include']['#access'] = FALSE;

  _ecenter_editing_process_field_image($form['field_image']);

  // Node type specific overrides
  switch ($node->type) {
    case 'wiki':
      $form['revision_information']['revision']['#access'] = FALSE;
      break;
  }
}

function _ecenter_editing_process_field_image(&$element) {
  $element['#theme'] = 'insert_multiple_values';
  $element['field_image_add_more']['#weight'] = 10;
  foreach (element_children($element) as $key) {
    if (!empty($element[$key]['_weight'])) {
      $element[$key]['_weight']['#type'] = 'value';
    }
  }
}
