<?php
// $Id$

/**
 * @file
 * Provides TinyMCE + Markdown integration via very simple Ajax.
 *
 * Based to some degree on ajax_markup module, so released under the GPL.
 */

/**
 * Implementation of hook_menu().
 */
function tinymce_markdown_menu() {
  $items['markdown2html'] = array(
    'page callback' => 'tinymce_markdown_markdown2html',
    'access callback' => 'tinymce_markdown_access',
    'type' => MENU_CALLBACK,
  );
  $items['html2markdown'] = array(
    'page callback' => 'tinymce_markdown_html2markdown',
    'access callback' => 'tinymce_markdown_access',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function tinymce_markdown_perm() {
  return array('access tinymce markdown converter');
}

/**
 * Convert html to markdown
 */
function tinymce_markdown_html2markdown() {
  
  require_once(dirname(__FILE__) . '/markdownify/markdownify.php');
  require_once(dirname(__FILE__) . '/markdownify/markdownify_extra.php');

  $markdownify = new Markdownify();
  $output = $markdownify->parseString($_POST['input']);

  drupal_set_header('Content-Type: text/javascript; charset=utf-8');
  echo json_encode(array('output' => $output));
  exit();
}

/**
 * Convert markdown to html
 */
function tinymce_markdown_markdown2html() {
  $output = _markdown_process($_POST['input'], -1);
  drupal_set_header('Content-Type: text/javascript; charset=utf-8');
  echo json_encode(array('output' => $output));
  exit();
}

/**
 * Check access to tinymce markdown converter
 */
function tinymce_markdown_access() {
  /*return user_access('access tinymce markdown converter') 
    && isset($_POST['token']) 
    && drupal_valid_token($_POST['token'], 'tinymce-markdown');*/
  return user_access('access tinymce markdown converter');
}

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function tinymce_markdown_wysiwyg_plugin($editor, $version) {
  if ($editor == 'tinymce' && version_compare($version, '3', '>')) {
    return array(
      'markdown' => array(
        'path' => drupal_get_path('module', 'tinymce_markdown') 
          .'/js/markdown_plugin.js',
        'extensions' => array('markdown' => t('Markdown')),
        'load' => TRUE,
      ),
    );
  }
}

/**
 * Enable tinymce_markdown 
 */
function tinymce_markdown_enable() {
  static $state;

  if (isset($state)) {
    return $state;
  }
  if (!user_access('access tinymce markdown converter')) {
    return $state = FALSE;
  }

  drupal_add_js(drupal_get_path('module', 'tinymce_markdown') 
    .'/js/tinymce_markdown.js');

  /*drupal_add_js(array(
    'token' => drupal_get_token('tinymce-markdown'),
  ), 'setting');*/

  return $state = TRUE;
}
