<?php

/**
 * @file relative_link_filter
 *
 * Provide site relative links. Based on code by Barry Jaspan.
 */

/**
 * Implementation of hook_filter_tips().
 */
function relative_link_filter_filter_tips($delta, $format, $long) {
  return relative_link_filter_filter('tip', $delta, $format, $long);
}

/**
 * Implementation of hook_filter().
 */
function relative_link_filter_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
  case 'list':
    return array(t('Site-relative links filter'));
   
  case 'no cache':
    return 0;
   
  case 'description':
  case 'tip':
    return t('Site-relative links such as &lt;a href="node/123"&gt; will work correctly.');
   
  case 'process':
    $text = preg_replace_callback('@(<(?:a|img)\s*[^>]*(?:href|src)=")((?:[^/#][-a-z0-9_./ ]*)?)("[^>]*>)@i', create_function('$m', 'return $m[1].url($m[2]).$m[3];'), $text);
    return $text;
   
  case 'settings':
    return;
   
  default:
    return $text;
  }
}
