<?php
// $Id$

/**
 * @file
 * E-Center network query interface.
 */
include_once('ecenter_network.features.inc');

// Load traceroute diff (to keep licensing issues clear)
require_once('ecenter_network_traceroute_diff.inc');

/**
 * Implementation of hook_menu().
 */
function ecenter_network_menu() {
  $items['network'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ecenter_network_select_form'),
    'access arguments' => array('access ecenter network'),
    'type' => MENU_CALLBACK,
  );

  $items['network/query'] = array(
    'page callback' => 'ecenter_network_display_data',
    'page arguments' => array(),
    'access arguments' => array('access ecenter network'),
    'type' => MENU_CALLBACK,
  );

  $items['network/health'] = array(
    'title' => 'Network health', 
    'page callback' => 'ecenter_network_health',
    'page arguments' => array(),
    'access arguments' => array('access ecenter network'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/settings/ecenter'] = array(
    'title' => 'E-Center Network',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ecenter_network_admin_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer ecenter network'),
    'description' => 'Configure the E-Center network tools.',
    'file' => 'ecenter_network.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function ecenter_network_perm() {
  return array('access ecenter network', 'administer ecenter network', 'debug ecenter network');
}

/**
 * Implementation of hook_theme().
 */
function ecenter_network_theme() {
  $options = array(
    'file' => 'ecenter_network.theme.inc',
    'path' => drupal_get_path('module', 'ecenter_network') .'/theme',
  );
  $registry = array(
    'ecenter_network_hop_option' => array(
      'arguments' => array(
        'hop' => NULL,
      )
    ) + $options,
   'ecenter_network_data' => array(
      'template' => 'ecenter-network-data',
      'arguments' => array(
        'data' => NULL,
        'params' => NULL,
      )
    ) + $options,
   'ecenter_network_recent_queries' => array(
      'arguments' => array('collapse' => NULL),
    ) + $options,
    'ecenter_network_recent_query' => array(
      'arguments' => array(
        'time' => NULL,
        'query' => NULL,
      ),
    ) + $options,
    'ecenter_network_hops' => array(
      'arguments' => array(
        'hops' => array(),
      ),
    ) + $options,
    'ecenter_network_end_to_end' => array(
      'template' => 'ecenter-network-end-to-end',
      'arguments' => array(
        'data' => NULL,
        'ads_data' => NULL,
        'timezone' => NULL,
      ),
    ) + $options,
    'ecenter_network_end_to_end_tables' => array(
      'arguments' => array(
        'tables' => NULL,
        'timezone' => NULL,
      ),
    ) + $options,
    'ecenter_network_utilization_table' => array(
      'arguments' => array(
        'table' => NULL,
        'hop' => NULL,
      ),
    ) + $options,
    'ecenter_network_format_default' => array(
      'arguments' => array(
        'value' => NULL,
        'type' => NULL,
        'measurement' => NULL,
        'units' => TRUE,
        'format' => NULL,
      ),
    ) + $options,
    'ecenter_network_format_default_label' => array(
      'arguments' => array(
        'measurement' => NULL,
        'type' => NULL,
        'direction' => NULL,
        'help' => FALSE,
      ),
    ) + $options,
    'ecenter_network_format_value' => array(
      'arguments' => array(
        'value' => NULL,
        'units' => NULL,
      ),
    ) + $options,
    'ecenter_network_health' => array(
      'template' => 'ecenter-network-health',
      'arguments' => array(
        'data' => NULL,
        'start' => NULL,
        'end' => NULL,
      ),
    ) + $options,
    'ecenter_network_health_row' => array(
      'arguments' => array(
        'metadata_count' => 0,
        'cached_data_count' => 0,
      ),
    ) + $options,
    'ecenter_network_site_centric_snmp_data' => array(
      'arguments' => array(
        'row' => NULL,
        'direction' => NULL,
      ),
    ) + $options,
  );
  return $registry;
}

/**
 * Implementation of hook_init().
 */
function ecenter_network_init() {
  if (arg(0) == 'network' && !arg(1)) {
    // Compression type
    $compression = variable_get('jquery_update_compression_type', 'none');
    $min = ($compression != 'none') ? '.'. $compression : '';

    // Openlayers
    openlayers_include();
    drupal_add_js(drupal_get_path('module', 'openlayers') .
      '/includes/layer_types/js/raw.js');
    drupal_add_js(drupal_get_path('module', 'ecenter_network')
      .'/js/openlayers.js');
    drupal_add_js(drupal_get_path('module', 'ecenter_network')
      .'/openlayers/ecenter_network_behavior_dynamicload.js');
    drupal_add_js(drupal_get_path('module', 'ecenter_network')
      .'/openlayers/ecenter_network_behavior_select.js');

    // jQuery UI: Force version 1.8, load libraries for datepicker and combobox
    jquery_ui_add(array('ui.widget', 'ui.mouse', 'ui.button', 'ui.position', 'ui.autocomplete', 'ui.datepicker'), '1.8');

    // jqPlot
    $jq_path = _jqplot_get_path();
    $tablechart_path = _jqplot_get_tablechart_path();
    drupal_add_css($jq_path .'/jquery.jqplot.css');
    drupal_add_js($jq_path .'/excanvas.min.js');
    drupal_add_js($jq_path .'/jquery.jqplot.js');
    drupal_add_js($jq_path .'/plugins/jqplot.dateAxisRenderer'. $min .'.js');
    drupal_add_js($jq_path .'/plugins/jqplot.highlighter'. $min .'.js');
    drupal_add_js($jq_path .'/plugins/jqplot.cursor'. $min .'.js');
    drupal_add_js($jq_path .'/plugins/jqplot.barRenderer'. $min .'.js');
    drupal_add_js($jq_path .'/plugins/jqplot.canvasTextRenderer'. $min .'.js');
    drupal_add_js($jq_path .'/plugins/jqplot.canvasAxisLabelRenderer'. $min .'.js');
    drupal_add_js(drupal_get_path('module', 'ecenter_network') .'/js/jqplot/jqplot.linehighlighter.js');
    drupal_add_js($tablechart_path .'/jquery.tablechart.js');
    drupal_add_js(drupal_get_path('module', 'jqplot') .'/js/jqplot-behaviors.js');

    // SVG
    drupal_add_css(libraries_get_path('jquery-svg') .'/jquery.svg.css');
    drupal_add_js(libraries_get_path('jquery-svg') .'/jquery.svg.js');

    // Traceroute
    drupal_add_js(drupal_get_path('module', 'ecenter_network') .'/js/jquery.traceroute.js');

    // Timezone handling
    drupal_add_js(drupal_get_path('module', 'date_timezone') .'/date_timezone.js');

    // Page behaviors
    drupal_add_js(drupal_get_path('module', 'ecenter_network') .'/js/behaviors.js');

    // Advanced help styling
    drupal_add_css(drupal_get_path('module', 'advanced_help') .'/help-icon.css');

    // @TODO overhaul
    $inline_css = array(
      '.ecenter-critical' => array('color' => variable_get('ecenter_network_threshold_critical_color', '#cc0000')),
      '.ecenter-marginal' => array('color' => variable_get('ecenter_network_threshold_marginal_color', '#fe890c')),
      '.ecenter-good' => array('color' => variable_get('ecenter_network_threshold_marginal_color', '#1c8a24')),
    );
    inline_css_add_css($inline_css);
  }
}

/**
 * E-center network health
 */
function ecenter_network_health() {
  $client = ecenter_network_get_client('503');

  extract(_ecenter_network_extract_query());

  if (!$start || !$end) {
    $inc = 30;
    module_load_include('inc', 'date_api', 'date_api_elements');
    $now = time();
    $start = date_make_date($now);
    $end = date_make_date($now);
    date_modify($start, '-24 hours');

    $utc = timezone_open('UTC');
    date_timezone_set($start, $utc);
    date_timezone_set($end, $utc);

    date_increment_round($start, $inc);
    date_increment_round($end, $inc);

    $start = date_format($start, 'Y-m-d H:i:s');
    $end = date_format($end, 'Y-m-d H:i:s');
  }

  $response = $client->getHealth($start, $end);
  if ($response['code'] == 200) {
    return theme('ecenter_network_health', $response['response'], $start, $end);
  }
  return 'this should be an error message';
}

/**
 * Primary selection form definition.
 */
function _ecenter_network_select_form() {
  global $user;
  extract(_ecenter_network_extract_query());

  // Initialize time-related variables
  $default_start = variable_get('ecenter_network_default_end', 7200);
  $offset = variable_get('ecenter_network_default_offset', 600);
  $now = time();
  
  // Map
  $preset = openlayers_preset_load('ecenter_network');
  $map = openlayers_render_map($preset->data, $preset->name);

  // Cache build time
  $form['build_time'] = array(
    '#type' => 'value',
    '#value' => time(),
  );

  // Don't disable submit or validate callbacks
  $form['#ahah_enable_handlers'] = TRUE;

  // Network map
  $form['network_wrapper'] = array(
    '#prefix' => '<div id="network-wrapper" class="clear-block">',
    '#suffix' => '</div>',
  );
  $form['network_wrapper']['network'] = array(
    '#prefix' => '<div id="network-map">',
    '#value' => $map,
    '#suffix' => '</div>',
  );

  // Select source and destination IP -- convoluted structure because of AHAH
  $form['network_wrapper']['query'] = array(
    '#prefix' => '<div id="query-wrapper">',
    '#suffix' => '</div>',
  );

  // Source IP
  $form['network_wrapper']['query']['src_wrapper'] = array(
    '#prefix' => '<div id="src-wrapper">',
    '#suffix' => '</div>',
  );
  $form['network_wrapper']['query']['src_wrapper']['src'] = array(
    '#title' => t('Source'),
    '#type' => 'combobox',
    '#cols' => 50,
    '#clear_button' => TRUE,
    '#options' => array('' => t('Select a source')),
    '#prefix' => '<div class="src-wrapper">',
    '#suffix' => '</div>',
    '#ahah' => array(
      'event' => 'change',
      'path' => ahah_helper_path(array('network_wrapper', 'query', 'dst_wrapper', 'dst')),
      'wrapper' => 'dst-wrapper',
    ),
  );

  // Destination IP
  $form['network_wrapper']['query']['dst_wrapper'] = array(
    '#prefix' => '<div id="dst-wrapper">',
    '#suffix' => '</div>',
  );
  $form['network_wrapper']['query']['dst_wrapper']['dst'] = array(
    '#title' => t('Destination'),
    '#type' => 'combobox',
    '#cols' => 50,
    '#clear_button' => TRUE,
    '#disabled' => TRUE,
    '#options' => array('' => t('Select a destination')),
    '#prefix' => '<div class="dst-wrapper">',
    '#suffix' => '</div>',
    '#ahah' => array(
      'event' => 'change',
      'path' => ahah_helper_path(array('results_wrapper', 'results')),
      'wrapper' => 'results-wrapper',
    ),
  );

  // Date select
  $form['network_wrapper']['query']['start'] = array(
    '#type' => 'date_text',
    '#title' => t('Start date'),
    '#default_value' => NULL,
    '#access' => FALSE,
  );
  $form['network_wrapper']['query']['end'] = array(
    '#type' => 'date_text',
    '#title' => t('End date'),
    '#default_value' => NULL,
    '#access' => FALSE,
  );

  $form['network_wrapper']['query']['recent_select'] = array(
    '#type' => 'radios',
    '#title' => t('Show recent results'),
    '#prefix' => '<div id="recent-select">',
    '#suffix' => '</div>',
    '#options' => array(
      3 => t('Last 3 hours'),
      6 => t('Last 6 hours'),
      12 => t('Last 12 hours'),
      24 => t('Last day'),
    ),
    '#default_value' => 3,
  );

  $form['network_wrapper']['query']['date_separator'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id="or-wrapper">',
    '#suffix' => '</div>',
    '#value' =>  t('Or'),
  );

  $form['network_wrapper']['query']['date_select'] = array(
    '#type' => 'date_popup',
    '#title' => t('Specify day'),
    '#prefix' => '<div id="date-select">',
    '#suffix' => '</div>',
    '#date_format' => 'Y-m-d',
    '#granularity' => array('year', 'month', 'day'),
    '#default_value' => NULL,
  );

  $form['network_wrapper']['query']['timezone_name'] = array(
    '#type' => 'combobox',
    '#title' => t('Timezone'),
    '#prefix' => '<div id="timezone-select">',
    '#suffix' => '</div>',
    '#default_value' => NULL,
    '#options' => date_timezone_names(),
  );

  $form['network_wrapper']['query']['help'] = array('#value' => 
    '<p class="instructions">'. t("The timezone used to display results. Default 
    timezone is determined from your system time and location.") .'</p>',
  );

  $form['network_wrapper']['query']['date_description'] = array(
    '#prefix' => '<div id="date-description-wrapper"><p>',
    '#suffix' => '</p></div>',
  );

  // Submit button
  $form['network_wrapper']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#attributes' => array('class' => 'no-js'),
  );

  // Data results display
  $form['results_wrapper'] = array(
    '#prefix' => '<div id="results-wrapper" class="clearfix">',
    '#suffix' => '</div>',
  );

  // For ahah helper
  $form['#tree'] = TRUE;

  return $form;
}

/**
 * Form snippet for ADS
 */
function ecenter_network_ads_form() {
  extract(_ecenter_network_extract_query());

  $form['ads_wrapper'] = array(
    '#prefix' => '<div id="ads-settings-wrapper">',
    '#suffix' => '</div>',
  );

  $form['ads_wrapper']['ads'] = array(
    '#id' => 'ads',
    '#name' => 'ads',
    '#type' => 'checkbox',
    '#title' => 'Use anomaly detection (experimental)',
    '#value' => FALSE,
    '#weight' => 0,
  );

  $form['ads_wrapper']['ads_settings'] = array(
    '#id' => 'ads-settings-fieldset',
    '#prefix' => '<div id="ads-settings">',
    '#suffix' => '</div>',
    '#type' => 'fieldset',
    '#title' => t('Anomaly detection settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['ads_wrapper']['ads_settings']['algorithm'] = array(
    '#id' => 'algorithm',
    '#name' => 'algorithm',
    '#title' => theme('advanced_help_topic', 'ecenter_network', 'ads_algorithm') . t('Algorithm'),
    '#type' => 'select',
    '#options' => array(
      'spd' => t('spd'),
      'apd' => t('apd'),
    ),
    '#attributes' => array('class' => 'ads-algorithm'),
    '#value' => (!empty($algorithm)) ? $algorithm : 'spd',
    '#weight' => 1,
  );

  $form['ads_wrapper']['ads_settings']['sensitivity'] = array(
    '#id' => 'sensitivity',
    '#name' => 'sensitivity',
    '#title' => theme('advanced_help_topic', 'ecenter_network', 'ads_sensitivity') . t('Sensitivity'),
    '#type' => 'textfield',
    '#size' => 5,
    '#id' => 'sensitivity',
    '#name' => 'sensitivity',
    '#value' => (!empty($sensitivity)) ? $sensitivity : 2,
    '#weight' => 2,
  );

  $form['ads_wrapper']['ads_settings']['elevation1'] = array(
    '#id' => 'elevation1',
    '#name' => 'elevation1',
    '#title' => theme('advanced_help_topic', 'ecenter_network', 'ads_elevation1') . t('Elevation 1'),
    '#type' => 'textfield',
    '#size' => 5,
    '#value' => (!empty($elevation1)) ? $elevation1 : 0.2,
    '#weight' => 3,
  );

  $form['ads_wrapper']['ads_settings']['elevation2'] = array(
    '#id' => 'elevation2',
    '#name' => 'elevation2',
    '#title' => theme('advanced_help_topic', 'ecenter_network', 'ads_elevation2') . t('Elevation 2'),
    '#type' => 'textfield',
    '#size' => 5,
    '#value' => (!empty($elevation2)) ? $elevation2 : 0.4,
    '#weight' => 4,
  );

  $form['ads_wrapper']['ads_settings']['swc'] = array(
    '#id' => 'swc',
    '#name' => 'swc',
    '#title' => theme('advanced_help_topic', 'ecenter_network', 'ads_swc') . t('Window count'),
    '#type' => 'textfield',
    '#size' => 5,
    '#value' => (!empty($swc)) ? $swc : 15,
    '#weight' => 5,
  );
  
  $form['ads_wrapper']['ads_submit'] = array(
    '#type' => 'submit',
    '#id' => 'ads-submit',
    '#name' => 'ads-submit',
    '#value' => t('Detect anomalies'),
    '#weight' => 5,
    '#attributes' => array('class' => 'ads-submit'),
  );

  return $form;
}

/**
 * Primary selection form.
 *
 * The basic form is defined in _ecenter_network_select_form. This function
 * primarily processes the form.
 */
function ecenter_network_select_form(&$form_state) {
  global $user;

  // Bail if the service is down
  ecenter_network_get_client('503');
  
  // Get base form and register with ahah_helper
  $form = _ecenter_network_select_form();
  ahah_helper_register($form, $form_state);

  extract(_ecenter_network_extract_query());

  // Refresh map
  ecenter_network_refresh_map('ecenter_network', 'openlayers-map-auto-id-0');

  // Set dates
  if (!empty($start)) {
    $form['network_wrapper']['query']['start']['#default_value'] = 
      _ecenter_network_utc_to_local($start);
  }
  if (!empty($end)) {
    $form['network_wrapper']['query']['end']['#default_value'] = 
      _ecenter_network_utc_to_local($end);
  }

  if (empty($timezone)) {
    $user_timezone = $user->timezone_name ? $user->timezone_name 
      : variable_get('date_default_timezone_name', NULL);
  }
  else {
    $user_timezone = $timezone;
  }
  
  $form['network_wrapper']['query']['timezone_name']['#default_value'] = $user_timezone;

  // Clear time selection if there's a query
  if (!empty($start) || !empty($end)) {
    $form['network_wrapper']['query']['recent_select']['#default_value'] = NULL;
  }

  $sources = ecenter_network_get_hops();
  $src_options[0] = '';
  foreach ($sources['hubs'] as $key => $hop) {
    $src_options['hub:'. $key] = theme('ecenter_network_hop_option', $hop);
  }
  $form['network_wrapper']['query']['src_wrapper']['src']['#options'] += $src_options;
  if (!empty($src)) {
    $form['network_wrapper']['query']['src_wrapper']['src']['#default_value'] = $src;
    list($src_type, $src_value) = explode(':', $src, 2);
    $destinations = ecenter_network_get_hops($src_value, $src_type);
    $dst_options[0] = '';
    foreach ($destinations['hubs'] as $key => $hop) {
      $dst_options['hub:'. $key] = theme('ecenter_network_hop_option', $hop);
    }
    $form['network_wrapper']['query']['dst_wrapper']['dst']['#options'] += $dst_options;
    $form['network_wrapper']['query']['dst_wrapper']['dst']['#disabled'] = FALSE;
  }

  if ($dst) {
    $form['network_wrapper']['query']['dst_wrapper']['dst']['#default_value'] = $dst;
  }

  if ($src && $dst && $start && $end) {
    $data = array(
      'drs' => ecenter_network_get_data($src, $dst, $start, $end)
    );

    $params = array(
      'src' => $src,
      'dst' => $dst,
      'start' => $start,
      'end' => $end,
      'timezone' => $user_timezone,
    );

    // If we've got the data (at bare minimum, a traceroute), delegate to rendering function
    if ($data) {
      drupal_add_js(array('ecenterNetwork' => array('tracerouteData' => 
        $data['drs']['traceroute']['diff'])), 'setting');
      drupal_add_js(array('ecenterNetwork' => array('tracerouteMaxLength' => 
        $data['drs']['traceroute']['traceroute_max'])), 'setting');

      if ($ads) {
        $data['ads'] = ecenter_network_get_ads_data($src, $dst, $start, $end, $algorithm, $detector_type, $sensitivity, $elevation1, $elevation2, $swc);
      }

      $form['results_wrapper']['results']['#value'] =
        theme('ecenter_network_data', $data, $params);
      $form['results_wrapper']['recent']['#value'] =
        theme('ecenter_network_recent_queries', TRUE);
    }
    else {
      $form['results_wrapper']['results']['#value'] = '<p>'. t('Whoops! No data was available for this query. If you believe there should be data for this query, send the site administrator feedback along with executed query, provided below.') .'</p>';
      $form['results_wrapper']['results']['#value'] .=
        '<p>'. l(t('Permalink'), 'network', array('query' => $params)) .'</p>';
    }
  }
  else {
    $form['results_wrapper']['#value'] = theme('ecenter_network_recent_queries');
  }
  return $form;
}

/**
 * Display ecenter data
 */
function ecenter_network_display_data() {
  if ($_GET['modal']) {
    modalframe_child_js();
  }
  $query = _ecenter_network_extract_query();
  $data = ecenter_network_get_data($query['src'], $query['dst'], $query['start'], $query['end']);
  $preset = openlayers_preset_load('ecenter_network');
  $map = openlayers_render_map($preset->data, $preset->name);
  return '<div class="page-network"><div id="content"><div id="network-wrapper">'.
   $map . theme('ecenter_network_data', $data, $query) .'</div></div></div>';
}

/**
 * Default submit handler for network form
 */
function ecenter_network_select_form_submit($form, &$form_state) {
  // Do what AHAH helper does on an AJAX call, to make form constructor a
  // little less crazy
  $inc = variable_get('ecenter_network_time_increment', 10);

  if ($form_state['values']['network_wrapper']['query']['recent_select']
    && !$form_state['values']['network_wrapper']['query']['date_select']) {

    $date = $form_state['values']['build_time'];
    $offset = 3600 * $form_state['values']['network_wrapper']['query']['recent_select'];
    $tz = timezone_open('UTC');
    $end = date_make_date($date, $tz, DATE_UNIX);
    $start = date_make_date($date - $offset, $tz, DATE_UNIX);

    date_increment_round($start, $inc);
    date_increment_round($end, $inc);

    $start = date_format($start, 'Y-m-d H:i:s');
    $end = date_format($end, 'Y-m-d H:i:s');
  }
  else if ($form_state['values']['network_wrapper']['query']['date_select']) {
    $date = $form_state['values']['network_wrapper']['query']['date_select'];
    $day = date_create($date, timezone_open('UTC'));

    $start = date_format($day, 'Y-m-d H:i:s');
    $end_date = date_modify($day, '+24 hours');
    $end = date_format($end_date, 'Y-m-d H:i:s');
  }

  $form_state['values']['network_wrapper']['query']['start'] = $start;
  $form_state['values']['network_wrapper']['query']['end'] = $end;

  // @TODO Set request variables -- seems hackish at this point
  $_REQUEST['network_wrapper']['query']['start']['date'] = $start;
  $_REQUEST['network_wrapper']['query']['end']['date'] = $end;

  $form_state['storage'] = $form_state['values'];
  $form_state['rebuild'] = TRUE;
}

/**
 * Get the E-Center Data Retrieval Service client
 *
 * All parameters optional
 *
 * @param $status_check
 *   If '503', return HTTP 503 page or redirect. If 'message', set message and
 *   continue. If FALSE, just return the client (default).
 * @param $type
 *   'drs' for Data Retrieval Service (default), 'ads' for Anomaly Detection
 *   Service
 * @param $name
 *   A unique name for this client (optional)
 */
function ecenter_network_get_client($status_check = FALSE, $type = 'drs', $name = NULL) {
  static $clients = array();

  require_once(dirname(__FILE__) . '/includes/ecenter_service.inc');
  switch ($type) {
    case 'drs':
      require_once(dirname(__FILE__) . '/includes/data_retrieval_service.inc');
      $klass = 'DataRetrievalService';
      $name = ($name) ? $name : 'drs_default';
      break;
    case 'ads':
      require_once(dirname(__FILE__) . '/includes/anomaly_detection_service.inc');
      $klass = 'AnomalyDetectionService';
      $name = ($name) ? $name : 'ads_default';
      break;
    default:
      drupal_set_message(t('Incorrect $type passed to client constructor'), 
        'error');
  }

  if (empty($clients[$name])) {
    $host = variable_get('ecenter_network_'. $type .'_host', 'localhost');
    $port = variable_get('ecenter_network_'. $type .'_port', 8000);
    $dir = variable_get('ecenter_network_'. $type .'_basedir', '');
    $timeout = variable_get('ecenter_network_'. $type .'_timeout', 30);
    $status_timeout = variable_get('ecenter_network_'. $type .'_status_timeout', 2);
    $clients[$name] = new $klass($host, $port, $dir, $timeout, 
      $status_timeout);
  }

  // Check client availability
  if ($status_check && !$clients[$name]->checkStatus()) {
    $message = t('!class client is not available.', array('!class' => $klass));
    watchdog('ecenter', $message, array(), WATCHDOG_ERROR);

    switch ($status_check) {
      case '503':
        drupal_set_header('HTTP/1.1 503 Service unavailable');
        // Keep old path for reference, and to allow forms to redirect to it.
        if (!isset($_REQUEST['destination'])) {
          $_REQUEST['destination'] = $_GET['q'];
        }
        print theme('page', '<div class="ecenter-fatal">'. $message .'</div>');
        exit();
      default:
        drupal_set_message($message, 'error');
    }
  }
  return $clients[$name];
}

/**
 * Get/cache data
 *
 * @param $src
 *   Source IP address
 * @param $dst
 *   Destination IP address
 * @param $start
 *   Start time, expressed in UTC, formatted as Y-m-d H:i:s
 * @param $end
 *   End time, expressed in UTC, formatted as Y-m-d H:i:s
 * @return
 *   An array of parsed data
 */
function ecenter_network_get_data($src, $dst, $start, $end) {
  global $user;
  static $results = array();

  $query = http_build_query(array(
    'src' => $src,
    'dst' => $dst,
    'start' => $start,
    'end' => $end,
  ));

  if (!array_key_exists($query, $results)) {
    $caching = variable_get('ecenter_network_data_cache_enabled', 0);
    if ($caching && $result = cache_get($query, 'cache_ecenter_data')) {
      $results[$query] = $result->data;
    }
    else {
      $resolution = variable_get('ecenter_network_drs_resolution', 50);
      $client = ecenter_network_get_client();
      $result = $client->getData($src, $dst, $start, $end, $resolution);
      if ($result['code'] == 200) {
        $data = ecenter_network_parse_response($result);
        if ($caching) {
          $expires = time() + variable_get('ecenter_network_data_cache_ttl', 3600);
          cache_set($query, $data, 'cache_ecenter_data', $expires);
        }
        $results[$query] = $data;
      }
      else { // Note that the static variable is NOT set in this case
        watchdog('ecenter_network',
          'Request (@url) failed with code @code (@response).',
          array('@url' => $result['url'], '@code' => $result['code'],
          '@response' => $result['response']), WATCHDOG_WARNING);
        return NULL;
      }
    }

    // Remember user's last queries: Anonymous users queries are stored in
    // their session; authenticated users queries are stored along with their
    // user object. Only capture successful queries.
    if (!empty($results[$query]) && $user->uid > 0) {
      $queries = $user->ecenter_network_queries;
      if (count($queries) >
        (variable_get('ecenter_network_recent_query_limit', 5))) {
        array_shift($queries);
      }
      $queries[$query] = array('time' => time(), 'query' => $query);
      user_save($user, array('ecenter_network_queries' => $queries));
    }
    else if (!empty($results[$query]) && isset($_COOKIE[session_name()])) {
      $queries = unserialize(sess_read('ecenter_network_queries'));
      if (count($queries) >
        (variable_get('ecenter_network_recent_query_limit', 5) - 1)) {
        array_shift($queries);
      }
      $queries[$query] = array('time' => time(), 'query' => $query);
      sess_write('ecenter_network_queries', serialize($queries));
    }

  }
  return $results[$query];
}

/**
 * Get/cache anomaly data
 *
 * @param $src
 *   Source IP address
 * @param $dst
 *   Destination IP address
 * @param $start
 *   Start time, expressed in UTC, formatted as Y-m-d H:i:s
 * @param $end
 *   End time, expressed in UTC, formatted as Y-m-d H:i:s
 * @return
 *   An array of parsed data
 */
function ecenter_network_get_ads_data($src, $dst, $start, $end, $algorithm = 'spd', $detector_type = NULL, $sensitivity = NULL, $elevation1 = NULL, $elevation2 = NULL, $swc = NULL) {
  $params = get_defined_vars();
  global $user;
  static $results = array();

  $query = http_build_query($params);

  if (!array_key_exists($query, $results)) {
    $resolution = variable_get('ecenter_network_ads_resolution', 1000);
    $client = ecenter_network_get_client('message', 'ads');
    foreach (array('owamp', 'bwctl') as $data_type) {
      $result = $client->getData($src, $dst, $start, $end, $data_type, $resolution, $algorithm, $detector_type, $sensitivity, $elevation1, $elevation2, $swc);
      if ($result['code'] == 200) {
        $data = ecenter_network_parse_ads_response($result);
        $results[$query][$data_type] = $data;
      }
      else { // Note that the static variable is NOT set in this case
        watchdog('ecenter_network',
          'Request (@url) failed with code @code (@response).',
          array('@url' => $result['url'], '@code' => $result['code'],
          '@response' => $result['response']), WATCHDOG_WARNING);
        return NULL;
      }
    }
  }
  return $results[$query];
}

/**
 * Get/cache site centric data
 *
 * @TODO Integrate parsing before cache is set
 *
 * @param $site
 *   Source IP address
 * @param $start
 *   Start time, expressed in UTC, formatted as Y-m-d H:i:s
 * @param $end
 *   End time, expressed in UTC, formatted as Y-m-d H:i:s
 * @return
 *   An array of parsed data
 */
function ecenter_network_get_site_centric_data($site, $start, $end) {
  global $user;
  static $results = array();

  $query = http_build_query(array(
    'src_hub' => $site,
    'start' => $start,
    'end' => $end,
  ));

  if (!array_key_exists($query, $results)) {
    $caching = variable_get('ecenter_network_site_data_cache_enabled', 0);
    if ($caching && $result = cache_get($query, 'cache_ecenter_site_data')) {
      $results[$query] = ecenter_network_parse_site_data($result->data, $site);
    }
    else {
      $resolution = variable_get('ecenter_network_site_data_resolution', 50);
      $client = ecenter_network_get_client();
      $result = $client->getSiteCentricData($site, $start, $end);
      if ($result['code'] == 200) {
        $data = $result['response'];
        if ($caching) {
          $expires = time() + variable_get('ecenter_network_site_data_cache_ttl', 7200);
          cache_set($query, $data, 'cache_ecenter_site_data', $expires);
        }
        $results[$query] = ecenter_network_parse_site_data($data, $site);
      }
      else { // Note that the static variable is NOT set in this case
        watchdog('ecenter_network',
          'Request (@url) failed with code @code (@response).',
          array('@url' => $result['url'], '@code' => $result['code'],
          '@response' => $result['response']), WATCHDOG_WARNING);
        return NULL;
      }
    }
  }
  return $results[$query];
}

/**
 * Get hops
 *
 * @param $src
 *   (optional) Source (hub name or IP) to determine potential destinations.
 *   If not supplied, list all potential source hops.
 * @param $src_type
 *   (optional) Source type ('hub' or 'ip')
 * @return
 *   An array of hop objects.
 */
function ecenter_network_get_hops($src = NULL, $src_type = 'hub') {
  static $hops = array();
  $src_key = (!empty($src)) ? $src : 'sources';

  if (empty($hops[$src_key])) {
    $caching = variable_get('ecenter_network_hop_cache_enabled', 0);
    if ($caching && $result = cache_get($src_key, 'cache_ecenter_hops')) {
      $hops[$src_key] = $result->data;
    }
    else {
      $client = ecenter_network_get_client();
      $result = $client->getHops($src, $src_type);
      if ($result['code'] == 200) {
        $data = ecenter_network_parse_hops($result['response']);
        $hops[$src_key] = $data;
        if ($caching) {
          $expires = time() + variable_get('ecenter_network_hop_cache_ttl', 300);
          cache_set($src_key, $data, 'cache_ecenter_hops', $expires);
        }
      }
      else {
        drupal_set_message(t('Request (@url) failed with code @code (@response).', 
          array('@url' => $result['url'], '@code' => $result['code'], '@response' => $result['response'])));
      }
    }
  }
  return $hops[$src_key];
}

/**
 * Get node
 */
function ecenter_network_get_node($ip) {
  static $nodes = array();
  if (empty($nodes[$ip])) {
    $caching = variable_get('ecenter_network_node_cache_enabled', 0);
    if ($caching && $result = cache_get($ip, 'cache_ecenter_nodes')) {
      $nodes[$ip] = $result->data;
    }
    else {
      $client = ecenter_network_get_client();
      $result = $client->getNode($ip);
      if ($result['code'] == 200) {
        $data = $result['response'];
        // Calculate netblock -- @TODO may not be necessary
        $data['netblock'] = long2ip(ip2long($data['ip_noted']) & 
          ~((1 << (32 - $data['netmask'])) - 1));
        $nodes[$ip] = $data;
        if ($caching) {
          $expires = time() + variable_get('ecenter_network_node_cache_ttl', 300);
          cache_set($ip, $data, 'cache_ecenter_nodes', $expires);
        }
      }
      else {
        drupal_set_message(t('Request (@url) failed with code @code (@response).', 
          array('@url' => $result['url'], '@code' => $result['code'], 
            '@response' => $result['response'])));
        return FALSE;
      }
    }
  }
  return $nodes[$ip];
}

/**
 * Parse Data Retrieval Sevice data
 *
 * Compatible with 3.4.x version of DRS. Several portions of the parser are
 * computationally expensive (a day's worth of data takes 200-300 ms to parse).
 *
 * @param $response
 *   A response object from the E-center webservice.
 * @return
 *   An array of parsed data
 */
function ecenter_network_parse_response($response) {
  $parsed_data = array();
  $data = $response['response'];
  $params = $response['parameters'];

  // Add hops to data structure
  foreach ($data['traceroute_nodes'] as $node_ip => $node) {
    $node = ecenter_network_get_node($node_ip);
    $node['id'] = str_replace('.', '_', $node_ip);
    $parsed_data['hops'][$node_ip] = $node + array('data' => 
      array(
        'snmp' => $data['snmp'][$node_ip],
      ),
    );
  }

  // Iterate through fwd/reverse + src/dst
  foreach (array('forward' => 'src', 'reverse' => 'dst') 
    as $direction => $end_type) {

    foreach (array('bwctl', 'owamp', 'pinger') as $test) {
      if (empty($data[$test])) {
        continue;
      }
      
      $parsed_data['end_to_end'][$test][$direction] = array();
      
      foreach ($data[$test] as $src => $destinations) {
        $processed_data = array();
        foreach ($destinations as $dst => $row) {
          if (($direction == 'forward' 
            && $params['src']['value'] == $row['src_hub']
            && $params['dst']['value'] == $row['dst_hub']) ||
            ($direction == 'reverse' 
            && $params['dst']['value'] == $row['src_hub']
            && $params['src']['value'] == $row['dst_hub'])) {
            foreach ($row['data'] as $timestamp => $measurements) {
              drupal_alter('ecenter_network_end_to_end_measurements', 
                $processed_data, $timestamp, $measurements);    
            }
            drupal_alter('ecenter_network_end_to_end_measurements_statistics',
              $processed_data); 
          }
        }

        if (!empty($processed_data)) {
          $parsed_data['end_to_end'][$test][$direction] += $processed_data;
        }

      }
    }

    // -- Process traceroute -- //
    $traceroute = array();
    $traceroute_direction = ($direction == 'forward') ? 'direct' : 'reverse';
    if (!empty($data[$traceroute_direction .'_traceroute'])) {
      foreach ($data[$traceroute_direction .'_traceroute'] as $series) {
        // Sort series so first hop is best candidate for most likely hop
        usort($series, '_ecenter_network_sort_series');
        $hop = array_shift($series);
        $hop += $parsed_data['hops'][$hop['hop_ip']];

        // Geolocate IP if no geo data available
        if (!$hop['longitude'] || !$hop['latitude']) {
          $geo = geoip_city($hop['hop_ip']);
          $hop['longitude'] = $geo->longitude;
          $hop['latitude'] = $geo->latitude;
          $hop['geolocated'] = TRUE;
        }
        $traceroute[$hop['hop_num'] - 1] = $hop;
      }

      // Sort by hop number
      ksort($traceroute);

      // Filter out hops which don't have SNMP data
      // @TODO may require differentiation between no SNMP data and no 
      // *available* SNMP data. 
      //$traceroute = array_filter($traceroute, '_ecenter_network_filter_traceroute');
      $parsed_data['traceroute'][$direction] = $traceroute;
    }
  }

  // Calculate diff
  if (!empty($parsed_data['traceroute']['forward']) 
    && !empty($parsed_data['traceroute']['reverse'])) {
    $forward = $parsed_data['traceroute']['forward'];
    $reverse = array_reverse($parsed_data['traceroute']['reverse']);

    $parsed_data['traceroute']['diff'] = ecenter_network_traceroute_diff($forward, $reverse);
    $parsed_data['traceroute']['traceroute_max'] = (count($forward) > count($reverse)) ? 
      count($forward) : count($reverse);
  }
  elseif (!empty($parsed_data['traceroute']['forward'])) {
    $diff = array();
    $forward = $parsed_data['traceroute']['forward'];
    foreach ($forward as $row) {
      $diff[] = array('match' => array('forward' => array($row)));
    }
    $parsed_data['traceroute']['diff'] = $diff;
    $parsed_data['traceroute']['traceroute_max'] = count($diff);
  }
  elseif (!empty($parsed_data['traceroute']['reverse'])) {
    $diff = array();
    $reverse = $parsed_data['traceroute']['reverse'];
    foreach ($reverse as $row) {
      $diff[] = array('match' => array('reverse' => array($row)));
    }
    $parsed_data['traceroute']['diff'] = $diff;
    $parsed_data['traceroute']['traceroute_max'] = count($diff);
  }
  
  return $parsed_data;
}

/**
 * Parse Anomaly Detection Service data
 *
 * Compatible with 3.4.x version of ADS.
 *
 * @param $response
 *   A response object from the ADS
 * @return
 *   An array of parsed data
 */
function ecenter_network_parse_ads_response($response) {
  $parsed_data = array();
  $data = $response['response'];
  $params = $response['parameters'];

  foreach (array('forward', 'reverse') as $direction) {
    foreach ($data as $src => $destinations) {
      foreach ($destinations as $dst => $row) {
        if (is_array($row['status']) &&
            (($direction == 'forward' 
            && $params['src']['value'] == $row['src_hub']
            && $params['dst']['value'] == $row['dst_hub']) ||
            ($direction == 'reverse' 
            && $params['dst']['value'] == $row['src_hub']
            && $params['src']['value'] == $row['dst_hub']))
          ) {
          $parsed_data[$direction] = $row['status'];
        } 
      }
    }
  }
  return $parsed_data;
}

/**
 * Parse 'site centric view' data
 *
 * Compatible with 3.4.x version of DRS. 
 *
 * @param $response
 *   A response object from the DRS
 * @return
 *   An array of parsed data
 */
function ecenter_network_parse_site_data($data, $site) {
  $parsed_data = array(
    'source' => $site,
  );
  foreach (array('direct_traceroute' => 'forward', 'reverse_traceroute' => 'reverse') as $key => $direction) {
    foreach ($data[$key] as $hub => $results) {
      $parsed_data['destinations'][$hub][$direction]['data'] = $results['snmp'];
      $parsed_data['destinations'][$hub][$direction]['themed'] = 
        theme('ecenter_network_site_centric_snmp_data', $results['snmp'], $direction);
    }
  }
  return $parsed_data;
}

/**
 * Filter traceroute results
 */
function _ecenter_network_filter_traceroute($hop) {
  return (!empty($hop['data']['snmp']));
}

/**
 * Implementation of ecenter_network_end_to_end_measurements_alter().
 */
function ecenter_network_ecenter_network_end_to_end_measurements_alter(&$data, $timestamp, $measurements) {
  unset($measurements['metaid'], $measurements['timestamp']);
  $timeseries = array();
  foreach ($measurements as $measurement => $value) {
    if ($measurement != 'sent') {
      $data[$measurement]['timeseries'][$timestamp] = (float) $value;
    }
  }
  if (!empty($data[$measurement]['timeseries'])) {
    ksort($data[$measurement]['timeseries']);
  }
}

/**
 * Implementation of ecenter_network_end_to_end_measurements_statistics_alter().
 */
function ecenter_network_ecenter_network_end_to_end_measurements_statistics_alter(&$data) {
  foreach ($data as $measurement => $measurements) {
    $values = $measurements['timeseries'];
    $count = count($values);
    $keys = array_keys($values);
    $data[$measurement]['statistics'] = array(
      'mean' => array_sum($values)/$count,
      'max' => max($values),
      'min' => min($values),
    );
  }
}

/**
 * Sort traceroute
 */
function _ecenter_network_sort_series($a, $b) {
  return ((int) $a['hop_delay'] > (int) $b['hop_delay']);
}

/**
 * Parse hops
 *
 * @param $hop_list
 *  List of hops returns from data service
 * @return
 *  Parsed array consisting of hubs, hops, and a combined list with urn-style
 *  keys (i.e. 'hub:BNL' and 'ip:127.0.0.1').
 */
function ecenter_network_parse_hops($hops) {
  $combined = array();
  $hubs = array();
  $ip_hops = array();

  usort($hops, '_ecenter_network_sort_hopname');

  foreach ($hops as $hop) {
    // First instance of hub
    if (empty($hubs[$hop['hub_name']])) {
      $hubs[$hop['hub_name']] = $hop;
      $combined['hub:'. $hop['hub_name']] = $hop + array('type' => 'hub');
    }
    $ip_hops[$hop['ip_noted']] = $hop;
    $combined['ip:'. $hop['ip_noted']] = $hop + array('type' => 'ip');
  }
  return array('combined' => $combined, 'hops' => $ip_hops, 'hubs' => $hubs);
}

/**
 * Callback for custom hop sort
 */
function _ecenter_network_sort_hopname($a, $b) {
  return strcmp($a['hub'], $b['hub']);
}

/**
 * Implementation of hook_jqplot_plugins().
 */
function ecenter_network_jqplot_plugins() {
  $path = drupal_get_path('module', 'ecenter_network') .'/js/jqplot';
  return array(
    'linehighlighter' => $path .'/jqplot.linehighlighter.js',
  );
}

/**
 * Implementation of hook_openlayers_presets().
 */
function ecenter_network_openlayers_presets() {

  $items = array();
  $openlayers_presets = new stdClass;
  $openlayers_presets->disabled = FALSE; 
  $openlayers_presets->api_version = 1;
  $openlayers_presets->name = 'ecenter_network';
  $openlayers_presets->title = 'E-Center Network';
  $openlayers_presets->description = 'E-Center network weathermap';
  $openlayers_presets->data = array(
    'width' => '660px',
    'height' => '400px',
    'image_path' => 'http://js.mapbox.com/theme/dark/',
    'css_path' => '',
    'proxy_host' => '',
    'hide_empty_map' => 0,
    'center' => array(
      'initial' => array(
        'centerpoint' => '-99.528515621067, 39.112468787821',
        'zoom' => '4',
      ),
    ),
    'behaviors' => array(
      'openlayers_behavior_navigation' => array(
        'zoomWheelEnabled' => 0,
      ),
      'openlayers_behavior_panzoom' => array(),
      'openlayers_behavior_fullscreen' => array(
        'activated' => 0,
      ),
      'ecenter_network_behavior_select' => array(
        'layers' => array(
          'ecenter_network_sites' => 'ecenter_network_sites',
          'ecenter_network_traceroute' => 'ecenter_network_traceroute',
        ),
      ),
      'ecenter_network_behavior_dynamicload' => array(),
      'ecenter_network_behavior_curves' => array(
        'layers' => array(
          'ecenter_network_traceroute' => 'ecenter_network_traceroute',
        ),
        'style' => 'ecenter_default',
      ),
    ),
    'default_layer' => 'world_glass',
    'layers' => array(
      'world_glass' => 'world_glass',
      'ecenter_network_sites' => 'ecenter_network_sites',
      'ecenter_network_traceroute' => 'ecenter_network_traceroute',
    ),
    'layer_activated' => array(
      'ecenter_network_sites' => 'ecenter_network_sites',
      'ecenter_network_traceroute' => 'ecenter_network_traceroute',
    ),
    'projection' => '900913',
    'styles' => array(
      'default' => 'ecenter_default',
      'select' => 'ecenter_selected',
      'temporary' => 'default',
    ),
    'preset_name' => 'ecenter_network',
  );
  $items["ecenter_network"] = $openlayers_presets;
  return $items;
}

/**
 * Implementation of hook_openlayers_styles().
 */
function ecenter_network_openlayers_styles() {
  $styles = array();

  // Default
  $style = new stdClass();
  $style->api_version = 1;
  $style->name = 'ecenter_default';
  $style->title = t('E-center style');
  $style->description = t('Basic e-center style.');
  $style->data = array(
    'pointRadius' => 6,
    'fillColor' => '#ffffff',
    'strokeColor' => '#0000aa',
    'strokeWidth' => 2,
    'fillOpacity' => 1,
  );
  $styles[$style->name] = $style;

  // Selected
  $style = new stdClass();
  $style->api_version = 1;
  $style->name = 'ecenter_selected';
  $style->title = t('E-center selected style');
  $style->description = t('Basic e-center style.');
  $style->data = array(
    'pointRadius' => 6,
    'fillColor' => '#ffffff',
    'strokeColor' => '#777777',
    'strokeWidth' => 2,
    'fillOpacity' => 1,
  );
  $styles[$style->name] = $style;

  // Curve
  $style = new stdClass();
  $style->api_version = 1;
  $style->name = 'ecenter_curve';
  $style->title = t('E-center curve style');
  $style->description = t('Basic e-center curve style.');
  $style->data = array(
    'pointRadius' => 0,
    'strokeColor' => '#777777',
    'strokeWidth' => 4,
  );
  $styles[$style->name] = $style;

  return $styles;
}

/**
 * Implementation of hook_openlayers_behaviors().
 */
function ecenter_network_openlayers_behaviors() {
  $behaviors = array(
    'ecenter_network_behavior_dynamicload' => array(
      'title' => t('E-Center Network: Dynamic Load'),
      'behavior' => array(
        'path' => drupal_get_path('module', 'ecenter_network') .'/openlayers',
        'file' => 'ecenter_network_behavior_dynamicload.inc',
        'class' => 'ecenter_network_behavior_dynamicload',
        'parent' => 'openlayers_behavior',
      ),
    ),
    'ecenter_network_behavior_select' => array(
      'title' => t('E-Center Network: Select behavior'),
      'behavior' => array(
        'path' => drupal_get_path('module', 'ecenter_network') .'/openlayers',
        'file' => 'ecenter_network_behavior_select.inc',
        'class' => 'ecenter_network_behavior_select',
        'parent' => 'openlayers_behavior',
      ),
    ),
    'ecenter_network_behavior_curves' => array(
      'title' => t('E-Center Network: Curved lines'),
      'behavior' => array(
        'path' => drupal_get_path('module', 'ecenter_network') .'/openlayers',
        'file' => 'ecenter_network_behavior_curves.inc',
        'class' => 'ecenter_network_behavior_curves',
        'parent' => 'openlayers_behavior',
      ),
    ),
    'ecenter_network_behavior_uncluster' => array(
      'title' => t('E-Center Network: Uncluster'),
      'behavior' => array(
        'path' => drupal_get_path('module', 'ecenter_network') .'/openlayers',
        'file' => 'ecenter_network_behavior_uncluster.inc',
        'class' => 'ecenter_network_behavior_uncluster',
        'parent' => 'openlayers_behavior',
      ),
    ),

  );
  return $behaviors;
}

/**
 * Implementation of hook_openlayers_layers().
 */
function ecenter_network_openlayers_layers() {
  $layers = array();
  $layers['ecenter_network_traceroute'] = ecenter_network_layers_traceroute();
  $layers['ecenter_network_sites'] = ecenter_network_layers_sites();

  $mapbox_layer = new stdClass;
  $mapbox_layer->disabled = FALSE; /* Edit this to true to make a default mapbox_layer disabled initially */
  $mapbox_layer->api_version = 1;
  $mapbox_layer->name = 'world_glass';
  $mapbox_layer->title = 'World glass';
  $mapbox_layer->description = 'A transparent world map base layer.';
  $mapbox_layer->data = array(
    'layername' => 'world-glass',
    'layer_type' => 'openlayers_layer_type_mapbox',
    'osm' => 0,
    'baselayer' => 1,
    'type' => 'png',
    'projection' => array('900913'),
    'resolutions' => array(
      0 => 156543.0339,
      1 => 78271.51695,
      2 => 39135.758475,
      3 => 19567.8792375,
      4 => 9783.93961875,
      5 => 4891.969809375,
      6 => 2445.9849046875,
      7 => 1222.9924523438,
      8 => 611.49622617188,
      9 => 305.74811308594,
    ),
    'maxExtent' => openlayers_get_extent('900913'), 
  );
  $layers['world_glass'] = $mapbox_layer;

  return $layers;
}

/**
 * Generate site map
 */
function ecenter_network_layers_sites() {
  extract(_ecenter_network_extract_query());
  $sources = ecenter_network_get_hops();

  // Calculate destinations
  if (!empty($src)) {
    list($src_type, $src_value) = explode(':', $src, 2);
    $hops = ecenter_network_get_hops($src_value, $src_type);
    if ($src_type == 'hub') {
      array_unshift($hops['hubs'], $sources['hubs'][$src_value]);
    }
    else if ($src_type == 'ip') {
      array_unshift($hops['hubs'], $sources['hops'][$src_value]);
    }
  }
  else {
    $hops = $sources;
  }

  // Create layer object
  $layer = new stdClass();
  $layer->api_version = 1;
  $layer->name = 'ecenter_network_sites';
  $layer->title = t('E-center Network Sites');
  $layer->description = '';
  $layer->data = array(
    'layer_type' => 'openlayers_layer_type_raw',
    'projection' => array('900913'),
  );

  if (!empty($src) && !empty($dst) && !empty($start) && !empty($end)) {
    $data = ecenter_network_get_data($src, $dst, $start, $end);
  }

  if (empty($src) || empty($dst) || empty($start) || empty($end)) {
    foreach ($hops['hubs'] as $hub) {
      $features[] = array(
        'wkt' => "POINT({$hub['longitude']} {$hub['latitude']})",
        'projection' => "4326",
        'style' => array(
          'pointRadius' => 5,
          'fillColor' => '#ffffff',
          'fillOpacity' => 1,
          'strokeColor' => '#4682b4',
          'strokeWidth' => 3,
          'strokeOpacity' => 1,
          'label' => $hub['hub_name'],
          'labelYOffset' => 17,
          'fontWeight' => 'bold',
          'fontSize' => '14px',
          'fontFamily' => '"Droid Sans", "Helvetica Neue", Helvetica, Verdana, sans-serif',
          'fontColor' => '#4682B4',
        ),
        'extra' => array(
          'ecenterID' => $hub['hub_name'], 
          'coords' => array('lat' => $hub['latitude'], 'lon' => $hub['longitude']),
        ),
      );
    }
    // @TODO remove when unclustering works
    _ecenter_network_layers_sites_rejigger($features);
    $layer->data['features'] = $features;
  }

  return $layer;
}

/**
 * @TODO HARDCODED BADNESS -- create "unclustering" behavior as replacement
 */
function _ecenter_network_layers_sites_rejigger(&$features) {
  foreach ($features as $k => $feature) {
    switch ($feature['extra']['ecenterID']) {
      case 'PPPL':
        $features[$k]['style']['labelYOffset'] = -20;
        $features[$k]['style']['labelXOffset'] = -5;
        break;
      case 'SLAC':
        $features[$k]['style']['labelYOffset'] = -5;
        $features[$k]['style']['labelXOffset'] = -30;
        break;
      case 'ANL':
        $features[$k]['style']['labelYOffset'] = -20;
        $features[$k]['style']['labelXOffset'] = 4;
        $lat = $features[$k]['extra']['coords']['lat'] - 0.4;
        $lon = $features[$k]['extra']['coords']['lon'];
        $features[$k]['wkt'] = "POINT({$lon} {$lat})";
        break;
      case 'NERSC':
        $lat = $features[$k]['extra']['coords']['lat'] + 0.4;
        $lon = $features[$k]['extra']['coords']['lon'] - 0.4;
        $features[$k]['style']['labelXOffset'] = -37;
        $features[$k]['style']['labelYOffset'] = 5;
        $features[$k]['wkt'] = "POINT({$lon} {$lat})";
        break;
      case 'LBL':
        $features[$k]['style']['labelXOffset'] = 24;
        $features[$k]['style']['labelYOffset'] = 5;
        $lat = $features[$k]['extra']['coords']['lat'] + .25;
        $lon = $features[$k]['extra']['coords']['lon'] + .8;
        $features[$k]['wkt'] = "POINT({$lon} {$lat})";
        break;
      case 'LLNL':
        $features[$k]['style']['labelXOffset'] = 15;
        $features[$k]['style']['labelYOffset'] = -15;
        $lat = $features[$k]['extra']['coords']['lat'] - .7;
        $lon = $features[$k]['extra']['coords']['lon'] + .15;
        $features[$k]['wkt'] = "POINT({$lon} {$lat})";
        break;
      case 'JGI':
        $features[$k]['style']['labelXOffset'] = 5;
        $features[$k]['style']['labelYOffset'] = 15;
        $lat = $features[$k]['extra']['coords']['lat'] + .7;
        $lon = $features[$k]['extra']['coords']['lon'] + .1;
        $features[$k]['wkt'] = "POINT({$lon} {$lat})";
        break;
      case 'SNLL':
        $features[$k]['style']['labelXOffset'] = 30;
        $features[$k]['style']['labelYOffset'] = 0;
        $lat = $features[$k]['extra']['coords']['lat'] - .2;
        $lon = $features[$k]['extra']['coords']['lon'] + .45;
        $features[$k]['wkt'] = "POINT({$lon} {$lat})";
        break;
      default:
        break;
    }
  }
}

/**
 * Generate dynamic raw layer data for E-center network
 */
function ecenter_network_layers_traceroute() {
  extract(_ecenter_network_extract_query());

  $layer = new stdClass();
  $layer->api_version = 1;
  $layer->name = 'ecenter_network_traceroute';
  $layer->title = t('Dynamic traceroute');
  $layer->description = '';
  $layer->data = array(
    'layer_type' => 'openlayers_layer_type_raw',
    'projection' => array('900913'),
    'options' => array(
      'rendererOptions' => array('zIndexing' => TRUE),
    ),
  );

  if ($src && $dst && $start && $end) {

    $data = ecenter_network_get_data($src, $dst, $start, $end);

    $traceroute = (!empty($data['traceroute']['forward'])) ? 
      $data['traceroute']['forward'] : $data['traceroute']['reverse'];

    if ($data && !empty($traceroute)) {

      // Initialize some counters, etc
      $old_hop = NULL;
      $count = count($traceroute);
      $i = 0;

      $features = array();
      foreach ($traceroute as $hop) {
        if ($hop['longitude'] && $hop['latitude']) {
          $features[] = array(
            'wkt' => "POINT({$hop['longitude']} {$hop['latitude']})",
            'projection' => "4326",
            'style' => array(
              'pointRadius' => 5,
              'fillColor' => '#ffffff',
              'strokeColor' => '#0000ff',
              'strokeWidth' => 3,
              'fillOpacity' => 1,
              'label' => $hop['hub'],
              'labelYOffset' => -16,
              'fontWeight' => 'bold',
              'fontSize' => '12px',
              'fontFamily' => '"Droid Sans", "Helvetica Neue", Helvetica, Verdana, sans-serif',
              'fontColor' => '#222222',
            ),
            'extra' => array('ecenterID' => $hop['hub']),
          );
        }
        $old_hop = $hop;
        $i += 1;

      }
    }

    if (!empty($features)) {
      _ecenter_network_layers_traceroute_rejigger($features);
    }
    $layer->data['features'] = $features;

  }
  return $layer;
}

/**
 * @TODO HARDCODED BADNESS along same lines as sites above
 */
function _ecenter_network_layers_traceroute_rejigger(&$features) {
  foreach ($features as $k => $feature) {
    switch ($feature['extra']['ecenterID']) {
      case 'bnl-mr2':
        $features[$k]['style']['labelXOffset'] = 35;
        $features[$k]['style']['labelYOffset'] = 0;
        break;
      case 'chic-cr1':
        $features[$k]['style']['labelXOffset'] = 10;
        $features[$k]['style']['labelYOffset'] = -15;
        break;
      case 'bost-cr1':
        $features[$k]['style']['labelXOffset'] = 10;
        $features[$k]['style']['labelYOffset'] = 15;
        break;
      case 'lbl-mr2':
        $features[$k]['style']['labelXOffset'] = -15;
        $features[$k]['style']['labelYOffset'] = 20;
        break;
      case 'star-cr1':
        $features[$k]['style']['labelXOffset'] = 35;
        $features[$k]['style']['labelYOffset'] = 10;
        break;
      case 'star-sdn1':
        $features[$k]['style']['labelXOffset'] = 30;
        break;
      case 'slac-mr2':
      case 'snv-mr2':
        $features[$k]['style']['labelXOffset'] = -35;
        $features[$k]['style']['labelYOffset'] = 0;
        break;
      case 'wash-sdn2':
        $features[$k]['style']['labelXOffset'] = -40;
        $features[$k]['style']['labelYOffset'] = 0;
        break;
      case 'sunn-cr1':
      case 'llnl-mr2':
      case 'wash-cr1':
        $features[$k]['style']['labelXOffset'] = 40;
        $features[$k]['style']['labelYOffset'] = 0;
        break;
      case 'pppl-rt2':
        $features[$k]['style']['labelYOffset'] = 15;
        break;
      default:
        break;
    }
  }
}

/**
 * Implementation of hook_openlayers_map_alter().
 */
function ecenter_network_openlayers_map_alter(&$map) {
  if ($map['preset_name'] == 'ecenter_network') {
    foreach ($map['layers'] as $name => $layer) {
      if ($layer['baselayer'] == TRUE) {
        $map['layers'][$name]['numZoomLevels'] = 12;
      }
    }
  }
}

/**
 * Implementation of hook_openlayers_map_preprocess_alter().
 */
function ecenter_network_openlayers_map_preprocess_alter(&$map) {
  // Add the new layers to the map array for our behavior to use
  if ($map['preset_name'] == 'ecenter_network') {
    $client = ecenter_network_get_client();

    // Get variables
    extract(_ecenter_network_extract_query());

    if ($src && $dst && $start && $end) {
      $data = ecenter_network_get_data($src, $dst, $start, $end);

      if ($data && !empty($data['forward'])) {
        $map['layers']['ecenter_traceroute'] = 'ecenter_traceroute';
        $map['layer_styles']['ecenter_traceroute'] = 'ecenter_default';
        $map['layer_activated']['ecenter_traceroute'] = 'ecenter_traceroute';
      }
    }
  }
  return $map;
}

/**
 * Refresh an Openlayers map
 *
 * This function is necessary because openlayers_render_map uses a small hack
 * and uses json_encode and adds map settings to the page header.  This
 * function adds the map array to the Drupal JS settings array no matter what,
 * so that AJAX/AHAH will work properly.
 *
 * @param $preset
 *   A string preset name.
 * @param $id
 *   Optional ID to use for map.
 */
function ecenter_network_refresh_map($preset, $id = NULL) {
  openlayers_include();
  $preset = openlayers_preset_load($preset);

  // Run map through build process
  $map = openlayers_build_map($preset->data);
  $map['id'] = (!empty($id)) ? $id : $map['id'];

  // Set proper JS settings
  if (empty($map['errors'])) {
    $js = array('openlayers' => array('maps' => array($map['id'] => $map)));
    drupal_add_js($js, 'setting');
  }
}

/**
 * Convert formatted local date string to formatted UTC date string
 *
 * @param $date
 *   A date string
 * @param $format
 *   Format to use for return value.
 * @return string
 *   Formatted, converted date
 */
function _ecenter_network_local_to_utc($date, $format = 'Y-m-d H:i:s', $tz = '') {
  if (empty($date)) {
    return NULL;
  }

  if (empty($tz)) {
    $tz = date_default_timezone_name(TRUE);
  }
  $adjusted = date_create($date, timezone_open($tz));
  date_timezone_set($adjusted, timezone_open('UTC'));
  return date_format($adjusted, $format);
}

/**
 * Adjust formatted UTC date string to formatted local date string
 *
 * @param $date
 *   A date string
 * @param $format
 *   Format to use for return value.
 * @return string
 *   Formatted, converted date
 */
function _ecenter_network_utc_to_local($date, $format = 'Y-m-d H:i:s', $tz = '') {
  if (empty($date)) {
    return NULL;
  }

  if (empty($tz)) {
    $tz = date_default_timezone_name(TRUE);
  }
  $adjusted = date_create($date, timezone_open('UTC'));
  date_timezone_set($adjusted, timezone_open($tz));
  return date_format($adjusted, $format);
}

/**
 * Convert Unix timestamp to formatted local date string
 *
 * @param $date
 *   A date string
 * @param $format
 *   Format to use for return value.
 * @return string
 *   Formatted, converted date
 */
function _ecenter_network_timestamp_to_local($date, $format = 'Y-m-d H:i:s', $tz = '') {
  if (empty($date)) {
    return NULL;
  }

  if (empty($tz)) {
    $tz = date_default_timezone_name(TRUE);
  }
  $adjusted = date_make_date($date, timezone_open('UTC'), DATE_UNIX);
  if (empty($tz)) {
    $tz = date_default_timezone_name(TRUE);
  }
  date_timezone_set($adjusted, timezone_open($tz));
  return date_format($adjusted, $format);
}

/**
 * Package query variables as an array
 *
 * E-Center queries can come from form input, or query string variables.  Let's
 * not worry about WHERE they came from during data processing.  Typically, you
 * should invoke by extract()ing the contents of the array.
 *
 * @return array
 *  An array of query values
 */
function _ecenter_network_extract_query() {
  $vars = array();

  if (!empty($_REQUEST['form_id']) && $_REQUEST['form_id'] == 'ecenter_network_select_form') {
    $vars = array(
      'src' => $_REQUEST['network_wrapper']['query']['src_wrapper']['src'],
      'dst' => $_REQUEST['network_wrapper']['query']['dst_wrapper']['dst'],
      'start' => _ecenter_network_local_to_utc($_REQUEST['network_wrapper']['query']['start']['date']),
      'end' => _ecenter_network_local_to_utc($_REQUEST['network_wrapper']['query']['end']['date']),
      'timezone' => $_REQUEST['network_wrapper']['query']['timezone_name'],

      'ads' => $_REQUEST['ads'],
      'algorithm' => $_REQUEST['algorithm'],
      'detector_type' => $_REQUEST['detector_type'],
      'sensitivity' => $_REQUEST['sensitivity'],
      'elevation1' => $_REQUEST['elevation1'],
      'elevation2' => $_REQUEST['elevation2'],
      'swc' => $_REQUEST['swc'],
    );
  }

  foreach (array('src', 'dst', 'start', 'end', 'timezone', 'ads', 'algorithm', 'detector_type', 'sensitivity', 'elevation1', 'elevation2', 'swc') as $key) {
    if (empty($vars[$key]) && !empty($_REQUEST[$key])) {
      $vars[$key] = $_REQUEST[$key];
    }
  }

  if (!empty($vars['ads']) && empty($vars['algorithm'])) {
    $vars['algorithm'] = 'spd';
  }

  return $vars;
}

/**
 * Implementation of template_preprocess_page().
 */
function ecenter_network_preprocess_page(&$vars) {
  // Add body class to weathermap
  if (arg(0) == 'network' && !arg(1)) {
    $vars['body_classes'] .= ' page-network-weathermap';
  }
}
