<?php
// $Id$

/**
 * @file
 * Provides hacks to Drupal content editing to match the E-center workflow.
 */

/**
 * Implementation hook_form_alter().
 */
function ecenter_forms_form_alter(&$form, &$form_state, $form_id) {
  // Node forms
  if ($form['#id'] == 'node-form') {
    // Remove options for internal Drupal workflow states
    $form['options']['promote']['#access'] = FALSE;
    $form['options']['sticky']['#access'] = FALSE;

    // Remove summary / teaser silliness
    $form['body_field']['teaser_include']['#access'] = FALSE;

    foreach ($form['#field_info'] as $field => $settings) {
      if (!empty($settings['widget']['insert'])) {
        $form[$field]['#title'] = t('Upload @type', array('@type' => $form[$field]['#title']));
        $form[$field]['#prefix'] = '<div class="field-insert" id="'. $form[$field]['#field_name'] .'">';
      }
    }
  }
}
