<?php
/**
 * Implementation of hook_wysiwyg_editor_settings_alter.
 */
function ecenter_editor_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->format == variable_get('ecenter_editor_format', NULL)) {
    drupal_add_css(drupal_get_path('module', 'ecenter_editor') 
      .'/css/tinymce.css');

    // Reorder buttons to put links at the front
    $buttons = array_flip(explode(',', $settings['theme_advanced_buttons1']));
    unset($buttons['linkit'], $buttons['unlink']);
    $buttons = array('linkit' => 1, 'unlink' => 1) + $buttons;
    $settings['theme_advanced_buttons1'] = implode(',', array_keys($buttons));
  }
}

function ecenter_editor_markdownify_html2markdown_postprocess_alter(&$output, $post) {
  // Output breaks added by Tinymce as newlines
  $output = str_replace(array('<br />', '<br>', '<br _moz_dirty="">'), "\r\n", $output);
}

// Disable some form settings
function ecenter_editor_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'filter_admin_format_form') {
    if (($format = variable_get('ecenter_editor_format', NULL))
      && $form['format']['#value'] == $format) {
      drupal_set_message(t('This input format is for use with the TinyMCE
        Markdown module. Changing the enabled filters have may undesireable
        results.'));
    }
  }
  
  if ($form_id == 'filter_admin_order') {
    if (($format = variable_get('ecenter_editor_format', NULL))
      && $form['format']['#value'] == $format) {
      drupal_set_message(t('This input format is for use with the TinyMCE
        Markdown module. Changing the filter order may have undesirable 
        results.'));
    }
  }

  if ($form_id == 'wysiwyg_profile_form') {
    if (($format = variable_get('ecenter_editor_format', NULL))
      && $form['format']['#value'] == $format) {

      drupal_set_message(t('This WYSWYG profile is managed by the TinyMCE
        Markdown module. Output settings and some plugins may not be changed.')
      );

      // Some plugins may not be removed: linkit and unlink because they are
      // required for wysiwyg icon reordering, markdown because the editor will
      // break without it.
      $form['buttons']['default']['unlink']['#value'] = TRUE;
      $form['buttons']['default']['unlink']['#disabled'] = TRUE;

      $form['buttons']['linkit']['linkit']['#value'] = TRUE;
      $form['buttons']['linkit']['linkit']['#disabled'] = TRUE;

      $form['buttons']['markdown']['markdown']['#value'] = TRUE;
      $form['buttons']['markdown']['markdown']['#disabled'] = TRUE;

      // All output settings are disabled
      foreach (element_children($form['output']) as $item) {
        $form['output'][$item]['#disabled'] = TRUE;
        $form['output'][$item]['#value'] = $form['output'][$item]['#default_value'];
      }
    }
  } 
}

/**
 * Implementation of hook_init().
 */
function ecenter_editor_init() {
  if (arg(0) == 'admin' && arg(1) == 'linkit' && arg(2) == 'dashboard') {
    drupal_add_css(drupal_get_path('module', 'ecenter_editor') 
      .'/css/linkit.css');
  }
}
