<?php
/** 
 * @file ecenter_editor.module
 *
 * This module forcibly installs an input format, WYSIWYG profile, and 
 * configuration for enabled filters. We use this "brute force" approach
 * because of the difficulty in exporting WYSIWYG profiles and input formats
 * to code.
 */

/**
 * Implementation of hook_wysiwyg_editor_settings_alter.
 */
function ecenter_editor_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->format == variable_get('ecenter_editor_format', NULL)) {
    drupal_add_css(drupal_get_path('module', 'ecenter_editor') 
      .'/css/tinymce.css');

    // Reorder buttons to put links at the front
    $buttons = array_flip(explode(',', $settings['theme_advanced_buttons1']));
    unset($buttons['linkit'], $buttons['unlink']);
    $buttons = array('linkit' => 1, 'unlink' => 1) + $buttons;
    $settings['theme_advanced_buttons1'] = implode(',', array_keys($buttons));
  }
}

function ecenter_editor_markdownify_html2markdown_postprocess_alter(&$output, $post) {
  // Output breaks added by Tinymce as newlines
  $output = str_replace(array('<br />', '<br>', '<br _moz_dirty="">'), "\r\n", $output);
}

// Disable some form settings
function ecenter_editor_form_alter(&$form, $form_state, $form_id) {
  // Node forms
  if ($form['#id'] == 'node-form') {
    // Remove options for internal Drupal workflow states
    $form['options']['promote']['#access'] = FALSE;
    $form['options']['sticky']['#access'] = FALSE;

    // Remove summary / teaser silliness
    $form['body_field']['teaser_include']['#access'] = FALSE;

    $form['content_edit'] = array(
      '#prefix' => '<div id="content-edit-wrapper" class="clearfix container">',
      '#suffix' => '</div>',
      'content_meta' => array(
        '#prefix' => '<div class="content-meta">',
        '#suffix' => '</div>',
        'revision_information' => $form['revision_information'],
        'taxonomy' => $form['taxonomy'],
        'og_nodeapi' => $form['og_nodeapi'],
      ),
      'body_field' => $form['body_field'],
    );
    
    unset($form['body_field'], $form['revision_information'], 
      $form['taxonomy'], $form['og_nodeapi']);

    $form['buttons']['#prefix'] = '<div class="buttons clearfix">';
    $form['buttons']['#suffix'] = '</div>';
  }
}

/**
 * Implementation of hook_init().
 */
function ecenter_editor_init() {
  if (arg(0) == 'admin' && arg(1) == 'linkit' && arg(2) == 'dashboard') {
    drupal_add_css(drupal_get_path('module', 'ecenter_editor') 
      .'/css/linkit.css');
  }
}
