<?php
// @TODO Add reset format for input format

include_once('editor_tinymce_markdown.features.inc');

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function editor_tinymce_markdown_wysiwyg_plugin($editor, $version) {
  if ($editor == 'tinymce' && version_compare($version, '3', '>')) {
    return array(
      'markdown' => array(
        'path' => drupal_get_path('module', 'editor_tinymce_markdown') 
          .'/js/markdown_plugin.js',
        'extensions' => array('markdown' => t('Markdown')),
        'load' => TRUE,
      ),
    );
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter.
 */
function editor_tinymce_markdown_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->format == _editor_tinymce_markdown_format()) {
    markdownify_on();

    drupal_add_css(drupal_get_path('module', 'editor_tinymce_markdown') 
      .'/css/tinymce.css');

    // Reorder buttons to put links at the front
    $buttons = array_flip(explode(',', $settings['theme_advanced_buttons1']));
    unset($buttons['linkit'], $buttons['unlink']);
    $buttons = array('linkit' => 1, 'unlink' => 1) + $buttons;
    $settings['theme_advanced_buttons1'] = implode(',', array_keys($buttons));
  }
}

/**
 * Get Markdown editor format id
 */
function _editor_tinymce_markdown_format($object = FALSE) {
  $format = db_fetch_object(db_query(
    'SELECT * FROM {filter_formats} WHERE name = "WYSIWYG Markdown"' 
  ));
  if ($object) {
    return $format; 
  }
  else {
    return $format->format;
  }
}


function editor_tinymce_markdown_markdownify_html2markdown_postprocess_alter(&$output, $post) {
  // Output breaks added by Tinymce as newlines
  $output = str_replace(array('<br />', '<br>', '<br _moz_dirty="">'), "\r\n", $output);
}

// Disable some form settings
function editor_tinymce_markdown_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'filter_admin_format_form') {
    if (($format = _editor_tinymce_markdown_format())
      && $form['format']['#value'] == $format) {
      drupal_set_message(t('This input format is for use with the TinyMCE
        Markdown module. Changing the enabled filters have may undesireable
        results.'));
    }
  }
  
  if ($form_id == 'filter_admin_order') {
    if (($format = _editor_tinymce_markdown_format())
      && $form['format']['#value'] == $format) {
      drupal_set_message(t('This input format is for use with the TinyMCE
        Markdown module. Changing the filter order may have undesirable 
        results.'));
      unset($form['names'], $form['submit'], $form['weights']);  
    }
  }

  if ($form_id == 'wysiwyg_profile_form') {
    if (($format = _editor_tinymce_markdown_format())
      && $form['format']['#value'] == $format) {

      drupal_set_message(t('This WYSWYG profile is managed by the TinyMCE
        Markdown module. Output settings and some plugins may not
        be changed.'));

      // Some plugins may not be removed: linkit and unlink because they are
      // required for wysiwyg icon reordering, markdown because the editor will
      // break without it.
      $form['buttons']['default']['unlink']['#value'] = TRUE;
      $form['buttons']['default']['unlink']['#disabled'] = TRUE;

      $form['buttons']['linkit']['linkit']['#value'] = TRUE;
      $form['buttons']['linkit']['linkit']['#disabled'] = TRUE;

      $form['buttons']['markdown']['markdown']['#value'] = TRUE;
      $form['buttons']['markdown']['markdown']['#disabled'] = TRUE;

      // All output settings are disabled
      foreach (element_children($form['output']) as $item) {
        $form['output'][$item]['#disabled'] = TRUE;
        $form['output'][$item]['#value'] = $form['output'][$item]['#default_value'];
      }
    }
  } 
}

/**
 * Implementation of hook_init().
 */
function editor_tinymce_markdown_init() {
  if (arg(0) == 'admin' && arg(1) == 'linkit' && arg(2) == 'dashboard') {
    drupal_add_css(drupal_get_path('module', 'editor_tinymce_markdown') 
      .'/css/linkit.css');
  }
}

/**
 * Implementation of hook_features_post_install().
 *
 * See http://drupal.org/node/981248 
 *
 * @TODO: Currently something is broken here and this does not run, or the
 * format is not installed when it is called.
 */
function editor_tinymce_markdown_features_post_install() {
  _editor_tinymce_markdown_install_profile();
}

/**
 * Install TinyMCE Markdown WYSIWYG profile
 *
 * @param $reset
 *   Boolean: if TRUE, reinstall profile
 */
function _editor_tinymce_markdown_install_profile($reset = FALSE) {
  $format = _editor_tinymce_markdown_format();

  if ($reset) {
    db_query('DELETE FROM {wysiwyg} WHERE format=%d', $format);
  } else if (db_result(db_query("SELECT format FROM {wysiwyg} WHERE 
      format=%d", $format))) {
    drupal_set_message(t('Markdown TinyMCE WYSIWYG profile has already been 
      installed.'));
    return TRUE;
  }

  // Configuration, for serialization 
  $settings = array(
    'default' => 1,
    'user_choose' => 0,
    'show_toggle' => 1,
    'theme' => 'advanced',
    'language' => 'en',
    'buttons' => array(
      'default' => array(
        'bold' => 1,
        'italic' => 1,
        'bullist' => 1,
        'numlist' => 1,
        'unlink' => 1,
        'image' => 1,
        'cut' => 1,
        'copy' => 1,
        'paste' => 1,
        'removeformat' => 1,
      ),
      'font' => array(
        'formatselect' => 1,
        'styleselect' => 1,
      ),
      'inlinepopups' => array(
        'inlinepopups' => 1,
      ),
      'markdown' => array(
        'markdown' => 1,
      ),
      'linkit' => array(
        'linkit' => 1,
      ),
    ),
    'toolbar_loc' => 'top',
    'toolbar_align' => 'left',
    'path_loc' => 'bottoms',
    'resizing' => 1,
    'verify_html' => 0,
    'preformatted' => 1,
    'convert_fonts_to_spans' => 0,
    'apply_source_formatting' => 0,
    'remove_linebreaks' => 0,
    'paste_auto_cleanup_on_paste' => 1,
    'block_formats' => 'p,h2,h3,h4,h5,h6,pre,div',
    'css_setting' => 'theme',
    'css_path' => NULL,
    'css_classes' => 'Align center=content-align-center
Align right=content-align-right
Float left=content-float-left
Float right=content-float-right
Introduction=content-introduction
Highlight=content-highlight
Large=content-large
Small=content-small
Loud=content-loud
Quiet=content-quiet',
  );  

  db_query(
    "INSERT INTO {wysiwyg} (format, editor, settings) VALUES (%d, '%s', '%s')", 
    $format, 'tinymce', serialize($settings)
  );
}
