<?php
/**
 * Implementation of hook_wysiwyg_plugin().
 */
function editor_tinymce_markdown_wysiwyg_plugin($editor, $version) {
  if ($editor == 'tinymce' && version_compare($version, '3', '>')) {
    return array(
      'markdown' => array(
        'path' => drupal_get_path('module', 'editor_tinymce_markdown') 
          .'/js/markdown_plugin.js',
        'extensions' => array('markdown' => t('Markdown')),
        'load' => TRUE,
      ),
    );
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter.
 */
function editor_tinymce_markdown_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->format == variable_get('editor_tinymce_markdown_format', NULL)) {
    markdownify_on();

    drupal_add_css(drupal_get_path('module', 'editor_tinymce_markdown') 
      .'/css/tinymce.css');

    // Reorder buttons to put links at the front
    $buttons = array_flip(explode(',', $settings['theme_advanced_buttons1']));
    unset($buttons['linkit'], $buttons['unlink']);
    $buttons = array('linkit' => 1, 'unlink' => 1) + $buttons;
    $settings['theme_advanced_buttons1'] = implode(',', array_keys($buttons));
  }
}

/**
 * Get Markdown editor format id
 */
function _editor_tinymce_markdown_format($object = FALSE) {
  $format = db_fetch_object(db_query(
    'SELECT * FROM {filter_formats} WHERE name = "WYSIWYG Markdown"' 
  ));
  if ($object) {
    return $format; 
  }
  else {
    return $format->format;
  }
}


function editor_tinymce_markdown_markdownify_html2markdown_postprocess_alter(&$output, $post) {
  // Output breaks added by Tinymce as newlines
  $output = str_replace(array('<br />', '<br>', '<br _moz_dirty="">'), "\r\n", $output);
}

// Disable some form settings
function editor_tinymce_markdown_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'filter_admin_format_form') {
    if (($format = variable_get('editor_tinymce_markdown_format', NULL))
      && $form['format']['#value'] == $format) {
      drupal_set_message(t('This input format is for use with the TinyMCE
        Markdown module. Changing the enabled filters have may undesireable
        results.'));
    }
  }
  
  if ($form_id == 'filter_admin_order') {
    if (($format = variable_get('editor_tinymce_markdown_format', NULL))
      && $form['format']['#value'] == $format) {
      drupal_set_message(t('This input format is for use with the TinyMCE
        Markdown module. Changing the filter order may have undesirable 
        results.'));
    }
  }

  if ($form_id == 'wysiwyg_profile_form') {
    if (($format = variable_get('editor_tinymce_markdown_format', NULL))
      && $form['format']['#value'] == $format) {

      drupal_set_message(t('This WYSWYG profile is managed by the TinyMCE
        Markdown module. Output settings and some plugins may not be changed.')
      );

      // Some plugins may not be removed: linkit and unlink because they are
      // required for wysiwyg icon reordering, markdown because the editor will
      // break without it.
      $form['buttons']['default']['unlink']['#value'] = TRUE;
      $form['buttons']['default']['unlink']['#disabled'] = TRUE;

      $form['buttons']['linkit']['linkit']['#value'] = TRUE;
      $form['buttons']['linkit']['linkit']['#disabled'] = TRUE;

      $form['buttons']['markdown']['markdown']['#value'] = TRUE;
      $form['buttons']['markdown']['markdown']['#disabled'] = TRUE;

      // All output settings are disabled
      foreach (element_children($form['output']) as $item) {
        $form['output'][$item]['#disabled'] = TRUE;
        $form['output'][$item]['#value'] = $form['output'][$item]['#default_value'];
      }
    }
  } 
}

/**
 * Implementation of hook_init().
 */
function editor_tinymce_markdown_init() {
  if (arg(0) == 'admin' && arg(1) == 'linkit' && arg(2) == 'dashboard') {
    drupal_add_css(drupal_get_path('module', 'editor_tinymce_markdown') 
      .'/css/linkit.css');
  }
}
