<?php
// @TODO Add reset format for input format

include_once('editor_tinymce_markdown.features.inc');

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function editor_tinymce_markdown_wysiwyg_plugin($editor, $version) {
  if ($editor == 'tinymce' && version_compare($version, '3', '>')) {
    markdownify_on();
    return array(
      'markdown' => array(
        'path' => drupal_get_path('module', 'editor_tinymce_markdown') 
          .'/js/markdown_plugin.js',
        'extensions' => array('markdown' => t('Markdown')),
        'load' => TRUE,
      ),
    );
  }
}

/**
 * Implementation of hook_wysiwyg_editor_settings_alter.
 */
function editor_tinymce_markdown_wysiwyg_editor_settings_alter(&$settings, $context) {
  $format = _editor_tinymce_markdown_format();
  if ($context['profile']->format == $format) {
    // Reorder buttons
    $buttons = array_flip(explode(',', $settings['theme_advanced_buttons1']));
    unset($buttons['linkit'], $buttons['unlink']);
    $buttons = array('linkit' => 1, 'unlink' => 1) + $buttons;
    $settings['theme_advanced_buttons1'] = implode(',', array_keys($buttons));
  }
}

/**
 * Get Markdown editor format id
 */
function _editor_tinymce_markdown_format() {
  return db_result(db_query(
    'SELECT format FROM {filter_formats} WHERE name = "%s"', 
    array('WYSIWYG Markdown')
  ));
}

// Disable some form settings

// Handle installation
