logger: "console"
log: "error"
warnings: 0
debug: 0
time_slice_secs: 1209600
show_errors: 1
route_cache: 1
auto_reload: 0
port: 8055
gearman:
   server: localhost
   port: 10221
plugins:
   DBIC:
     dbix:
       schema_class: Ecenter::DB
       dsn: dbi:mysql:localhost:dbname=ecenter_data
       user: ecenter
       pass: ecenter2010
       debug: 0
       options:
          ShowErrorStatement: 1
          RaiseError: 1
          PrintError: 1
          AutoCommit: 1
   Database:
     connections:
       ecenter:
          driver: mysql
          database: ecenter_data
          host: localhost
          username: ecenter
          password: ecenter2010
          connection_check_threshold: 10
          debug: 0
          dbi_params:
             ShowErrorStatement: 1
             RaiseError: 1
             PrintError: 1
             AutoCommit: 1
