<?php
// $Id$

/**
 * @file
 * Provides custom blocks for E-Center project.
 */

/**
 * Implements hook_theme().
 */
function ecenter_blocks_theme() {
  $path = array('path' => drupal_get_path('module', 'ecenter_blocks') .'/tpl');
  return array(
    'ecenter_blocks_login' => array('arguments' => array(), 'template' => 'ecenter-blocks-login') + $path,
  );
}

/**
 * Implements hook_block().
 */
function ecenter_blocks_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['login'] = array(
        'info' => t('E-Center Blocks: Login block'),
      );
      return $blocks;
    case 'view': default:
      return array(
        'content' => theme('ecenter_blocks_'. $delta),
      );
  }
}

function template_preprocess_ecenter_blocks_login(&$vars) {
  global $user;
  if ($user->uid > 0) {
    $links[] = t('Logged in as <span class="bold">@user</span>', array('@user' => $user->name));
    $links[] = l('Settings', 'user');
    $links[] = l(t('Logout'), 'logout');
  }
  else {
    $links[] = l(t('Login to E-center'), 'user');
  }
  $vars['links'] = $links;
  $vars['content'] = theme('item_list', $links);
}
