<?php

include_once('ecenter_user.features.inc');

/**
 * Implementation of hook_form_FORM_ID_form_alter().
 */
function ecenter_user_form_user_profile_form_alter(&$form, $form_state) {
  $account = $form['_account']['#value'];

  $form['ecenter'] = array(
    '#title' => t('E-Center settings'),
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
  );

  $hubs = ecenter_network_get_hops();
  $options[0] = '';
  foreach ($hubs['hubs'] as $key => $hop) {
    $options[$key] = theme('ecenter_network_hop_option', $hop);
  }

  $form['ecenter']['ecenter_default_hub'] = array(
    '#title' => t('Default hub'),
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => (!empty($account->ecenter_default_hub)) 
      ? $account->ecenter_default_hub : NULL,
    '#description' => t("The default hub for use in the site centric view and
      other places where a default hub is required."),
  );
}
