<?php

/**
 * @file theming_hacks.module
 *
 * Auto-detect and override CSS files without registration in a theme's
 * .info file.  This is a simple convenience, but it is fast and makes
 * CSS feel consistent with tpl replacement.
 *
 * It is critical that this module fire late in Drupal execution stack. The 
 * module installs with a default weight of '9999' which should be sufficient 
 * in most instances.
 */

/**
 * Implementation of template_preprocess_page().
 *
 * Overrides CSS.
 */
function theming_hacks_preprocess_page(&$variables, $hook) {
  $variables['styles'] = theming_hacks_get_css();
}

/**
 * This function overrides the default Drupal CSS setting behavior.  If a CSS
 * file of the same name as a module or system CSS file exists in the current
 * theme under the 'css' folder, then we use it *instead* of the 
 * Drupal/module-provided CSS file.  
 *
 * If the CSS file does not exist and the current theme is a subtheme, we
 * search up the base theme tree to see if it exists in a parent theme.
 *
 * Becase this can be accomplished by registering CSS files with the same names as
 * the module-provided CSS files in your .info file, this is only for convenience.
 *
 * @return 
 *   Rendered Drupal CSS
 */
function theming_hacks_get_css() {
  global $base_theme_info, $theme_info;

  $css = array();
  $old_css = drupal_add_css();

  $theme_info_path = explode('/', $theme_info->filename);
  array_pop($theme_info_path);
  $path_to_theme = implode('/', $theme_info_path);

  foreach ($old_css as $section=>$type) {
    foreach ($type as $type_name=>$css_file) {
      foreach ($css_file as $path=>$enabled) {
        $file = array_pop(explode('/', $path));  

        // Find override in current theme
        $override = file_scan_directory($path_to_theme .'/css', '^'. $file .'$', array('.', '..', 'CVS'));

        // If no override exists in current theme, look at parent themes
        if (empty($override) && !empty($GLOBALS['base_theme_info'])) {
          foreach ($base_theme_info as $base_theme) {
            $info_path = explode('/', $base_theme->filename);
            array_pop($info_path);
            $base_theme_path = implode('/', $info_path);
            if ($new_override = file_scan_directory($base_theme_path .'/css', $file .'$', array('.', '..', 'CVS'))) {
              $override = $new_override;
            }
          }
        }
        $override = array_pop($override);

        if (!empty($override)) {
          $css[$section][$type_name][$override->filename] = $enabled;
        }
        else {
          $css[$section][$type_name][$path] = $enabled;
        }
      }
    }
  }
  return drupal_get_css($css);
}
