<?php
// $Id$

/**
 * @file
 * E-Center core module and features
 */
include_once('ecenter_core.features.inc');

/**
 * Implementation of hook_theme().
 */
function ecenter_core_theme() {
  $path = array('path' => drupal_get_path('module', 'ecenter_core') .'/tpl');
  $blocks = ecenter_core_block();

  $theme = array();
  foreach ($blocks as $block => $info) {
    $theme['ecenter_core_'. $block .'_block'] = array(
      'arguments' => array(),
      'template' => 'ecenter-'. $block .'-block',
    ) + $path;
  }
  return $theme;
}

/**
 * Implementation of hook_menu().
 */
function ecenter_core_menu() {
  $items = array();
  $items['ecenter/timezone'] = array(
    'title' => 'E-Center user\'s timezone',
    'page callback' => 'ecenter_core_timezone',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_init().
 */
function ecenter_core_init() {
  // Force load AHAH
  drupal_add_js('misc/ahah.js');
  drupal_add_js(drupal_get_path('module', 'ecenter_core') .'/js/ahah.js');
}

/**
 * Implementation of hook_block().
 */
function ecenter_core_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['login'] = array(
        'info' => t('E-Center: Login block'),
      );
      $blocks['dashboard_login'] = array(
        'info' => t('E-Center: Dashboard login block'),
        'cache' => BLOCK_NO_CACHE,
      );
      $blocks['sponsors'] = array(
        'info' => t('E-Center: Sponsors block'),
      );
      $blocks['site_info'] = array(
        'info' => t('E-Center: Site info'),
      );
      return $blocks;
    case 'view': default:
      return array(
        'content' => theme('ecenter_core_'. $delta .'_block'),
      );
  }
}

/**
 * Implementation of hook_form_alter().
 */
function ecenter_core_form_alter(&$form, &$form_state, $form_id) {
  $form['#attributes']['class'] = (!empty($form['#attributes']['class'])) ? $form['#attributes']['class'] .' ' : '';
  $form['#attributes']['class'] .= 'form-id-'. $form_id;

  switch ($form_id) {
    case 'search_block_form':
      unset($form['search_block_form']['#title']);
  }
}

/**
 * Dashboard login block form
 */
function ecenter_core_dashboard_login() {
  $form = array(
    '#action' => url($_GET['q'], array('query' => drupal_get_destination())), 
    '#id' => 'user-login-form', 
    '#validate' => user_login_default_validators(), 
    '#submit' => array('user_login_submit'),
  ); 
  $form['name'] = array(
    '#type' => 'textfield', 
    '#title' => t('Username'), 
    '#maxlength' => USERNAME_MAX_LENGTH, 
    '#size' => 15, 
    '#required' => TRUE,
  );
  $form['pass'] = array(
    '#type' => 'password', 
    '#title' => t('Password'), 
    '#maxlength' => 60, 
    '#size' => 15, 
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Log in'),
  );
  if (variable_get('user_register', 1)) {
    $form['create'] = array(
      '#type' => 'markup',
      '#value' => l(t('Register new account'), 'user/register', array('attributes' => array('title' => t('Create a new user account.')))),
      '#prefix' => '<span class="register-link">',
      '#suffix' => '</span>',
    );
  }
  $form['alt_login'] = array(
    '#type' => 'markup',
    '#value' => t('Log in with') .' '. l(t('Shibboleth'), shib_auth_generate_login_url()) .' '. t('or').' '. l(t('OpenID'), 'user'),
    '#prefix' => '<div class="alt-login-link">',
    '#suffix' => '</div>',
  );
  $form['old_pass'] = array(
    '#type' => 'markup',
    '#value' => t('Forgot your password?') .' '. l(t('Request a new one.'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.')))),
    '#prefix' => '<div class="old-pass-link">',
    '#suffix' => '</div>',
  );
  return $form;
}

/**
 * Timezone callback (similar to date_timezone's user_timezone function
 * but with GeoIP location, etc)
 */
function ecenter_core_timezone($abbr = '', $offset = -1, $dst = NULL) {
  require_once('timezone.php');
  global $_REQUEST;
  $now = date_create();

  // Geolocate based on client IP
  if ($_SERVER['HTTP_X_FORWARDED_FOR']) {
    $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
  } 
  else {
    $ip = $_SERVER['REMOTE_ADDR'];
  }
  $city = geoip_city($ip);
  
  if ($city) {
    $ip_tz_name = get_time_zone($city->country_code, $city->region);
    $ip_tz = timezone_open($ip_tz_name);
    $ip_offset = timezone_offset_get($ip_tz, $now);

    // If client offset and IP offset match, our work is done
    if ($ip_offset == $offset) {
      return drupal_json($ip_tz_name);
    }
  }

  // If geolocated TZ is not same as client timezone, return best guess for
  // client timezone.
  $abbr = $abbr ? $abbr : '';
  $client_tz_name = timezone_name_from_abbr($abbr, intval($offset), $dst);
  return drupal_json($client_tz_name);
}

/**
 * Theme login block
 */
function template_preprocess_ecenter_core_login_block(&$vars) {
  global $user;
  if ($user->uid > 0) {
    $links[] = theme('user_picture', $user);
    $links[] = t('Logged in as <span class="bold">@user</span>', array('@user' => $user->name));
    $links[] = l('Settings', 'user');
    $links[] = l(t('Logout'), 'logout');
  }
  else {
    $links[] = l(t('Login to E-center'), 'user');
  }
  $vars['links'] = $links;
  $vars['content'] = theme('item_list', $links);
}

/**
 * Theme sponsor list 
 */
function template_preprocess_ecenter_core_sponsors_block(&$vars) {
  $vars['sponsors'] = array(
    l(t('Fermi National Accelerator Lab'), 'http://www.fnal.gov', 
      array('attributes' => array('class' => 'fnal replace'))), 
    l(t('U.S. Department of Energy Office of Science'), 'http://www.science.doe.gov', 
      array('attributes' => array('class' => 'doe replace'))), 
    l(t('Energy Science Net'), 'http://es.net', 
      array('attributes' => array('class' => 'esnet replace'))), 
    l(t('Bucknell University'), 'http://bucknell.edu', 
      array('attributes' => array('class' => 'bucknell replace'))), 
  );
}

/**
 * Theme site info block
 */
function template_preprocess_ecenter_core_site_info_block(&$vars) {}

/**
 * Theme dashboard login block
 */
function template_preprocess_ecenter_core_dashboard_login_block(&$vars) {
  $vars['form'] = drupal_get_form('ecenter_core_dashboard_login');
}
